### ISSUE TITLE
YOLONAS AS A DETECTOR

### ISSUE THREAD

**Issue by Choneke** [mikel-brostrom/yolo_tracking#1005]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Thank you for this work. I trained my YOLONAS on a custom dataset. However, when I use it as a detector for evaluating tracking with Bytetracker and all other trackers, it does not provide a tracking file or any results (Tracker file not found: D\yolo_tracking\examples\runs\val\exp10\labels\trackV000.txt). On the other hand, when I use another detector, it works fine. Is there any way to resolve this?  I provide the command and all other details below:

```
(yolotracking2) D\yolo_tracking>python examples/val.py --yolo-model examples/weights/yolonass_bestweight_EP250.pth --tracking-method bytetrack --benchmark MOTCUSTOM
val: yolo_model=examples/weights/yolonass_bestweight_EP150.pth, reid_model=D\yolo_tracking\examples\weights\mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=bytetrack, name=exp, classes=['0'], project=D\yolo_tracking\examples\runs\val, exist_ok=False, benchmark=MOTCUSTOM, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
2023-07-19 08:38:46.143 | INFO     | __main__:download_mot_eval_tools:64 - Eval repo already downloaded
2023-07-19 08:38:46.148 | INFO     | __main__:eval:195 - Staring evaluation process on D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV000\trackV000
2023-07-19 08:38:57.025 | SUCCESS  | __main__:eval:227 - D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV000\trackV000 evaluation succeeded
2023-07-19 08:38:57.028 | INFO     | __main__:eval:195 - Staring evaluation process on D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV001\trackV001
2023-07-19 08:39:08.056 | SUCCESS  | __main__:eval:227 - D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV001\trackV001 evaluation succeeded
2023-07-19 08:39:08.059 | INFO     | __main__:eval:195 - Staring evaluation process on D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV002\trackV002
2023-07-19 08:39:19.076 | SUCCESS  | __main__:eval:227 - D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV002\trackV002 evaluation succeeded
2023-07-19 08:39:19.079 | INFO     | __main__:eval:195 - Staring evaluation process on D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV003\trackV003
2023-07-19 08:39:30.123 | SUCCESS  | __main__:eval:227 - D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV003\trackV003 evaluation succeeded
2023-07-19 08:39:30.127 | INFO     | __main__:eval:195 - Staring evaluation process on D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV004\trackV004
2023-07-19 08:39:41.234 | SUCCESS  | __main__:eval:227 - D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV004\trackV004 evaluation succeeded
2023-07-19 08:39:41.238 | INFO     | __main__:eval:195 - Staring evaluation process on D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV005\trackV005
2023-07-19 08:39:52.463 | SUCCESS  | __main__:eval:227 - D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train\trackV005\trackV005 evaluation succeeded
val: yolo_model=examples/weights/yolonass_bestweight_EP150.pth, reid_model=D\yolo_tracking\examples\weights\mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=bytetrack, name=exp, classes=['0'], project=D\yolo_tracking\examples\runs\val, exist_ok=False, benchmark=MOTCUSTOM, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
2023-07-19 08:39:53.311 | ERROR    | __main__:eval:260 - Traceback (most recent call last):
  File "D\yolo_tracking\examples\val_utils\scripts\run_mot_challenge.py", line 84, in <module>    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "D\yolo_tracking\examples\val_utils\trackeval\datasets\mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: labels//trackV000.txt

2023-07-19 08:39:53.314 | ERROR    | __main__:eval:261 - Error importing BURST due to missing underlying dependency: No module named 'tabulate'

Eval Config:
USE_PARALLEL         : True
NUM_PARALLEL_CORES   : 4
BREAK_ON_ERROR       : True
RETURN_ON_ERROR      : False
LOG_ON_ERROR         : D\yolo_tracking\examples\val_utils\error_log.txt
PRINT_RESULTS        : True
PRINT_ONLY_COMBINED  : False
PRINT_CONFIG         : True
TIME_PROGRESS        : True
DISPLAY_LESS_PROGRESS : False
OUTPUT_SUMMARY       : True
OUTPUT_EMPTY_CLASSES : True
OUTPUT_DETAILED      : True
PLOT_CURVES          : True

MotChallenge2DBox Config:
PRINT_CONFIG         : True
GT_FOLDER            : D\yolo_tracking\examples\val_utils\data\MOTCUSTOM\train
TRACKERS_FOLDER      : D\yolo_tracking\examples\runs\val\exp10
OUTPUT_FOLDER        : None
TRACKERS_TO_EVAL     : ['labels']
CLASSES_TO_EVAL      : ['pedestrian']
BENCHMARK            :
SPLIT_TO_EVAL        : train
INPUT_AS_ZIP         : False
DO_PREPROC           : True
TRACKER_SUB_FOLDER   :
OUTPUT_SUB_FOLDER    :
TRACKER_DISPLAY_NAMES : None
SEQMAP_FOLDER        : None
SEQMAP_FILE          : None
SEQ_INFO             : {'trackV000': None, 'trackV001': None, 'trackV002': None, 'trackV003': None, 'trackV004': None, 'trackV005': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt
SKIP_SPLIT_FOL       : True
Tracker file not found: D\yolo_tracking\examples\runs\val\exp10\labels\trackV000.txt
```

**Comment by mikel-brostrom** [comment]
Do you have the latest version? I could replicate this before my last merge :smile:

**Comment by Choneke** [comment]
> Do you have the latest version? I could replicate this before my last merge 😄

Which latest version: You mean the latest version for yolonas OR yolo_tracking?

**Comment by Choneke** [comment]
> You also need to adapt this piece of code.
> 
> https://github.com/mikel-brostrom/yolo_tracking/blob/0752c7eaed41183c0ebc8ac8a31044b365817d7c/examples/detectors/strategy/yolonas.py#L13-L16
 Sorry, can you elaborate more on this?, what do I have to do?

**Comment by mikel-brostrom** [comment]
> Which latest version: You mean the latest version for yolonas OR yolo_tracking?

yolo_tracking

**Comment by mikel-brostrom** [comment]
> Sorry, can you elaborate more on this?, what do I have to do?

Change this:

https://github.com/mikel-brostrom/yolo_tracking/blob/0752c7eaed41183c0ebc8ac8a31044b365817d7c/examples/detectors/strategy/yolonas.py#L13-L16

to:

```
self.model = models.get(
    'yolo_nas_s',
    num_classes=<the-number-of-classes-in-your-model>,
    checkpoint_path =<path-to-your-weights.pt>
)
```

It is impossible for me to infer which YOLONAS model you trained and its number of classes as this is not stored as metadata in the model itself. So you sadly have to configure this yourself @Choneke

**Comment by Choneke** [comment]
> > Sorry, can you elaborate more on this?, what do I have to do?
> 
> Change this:
> 
> https://github.com/mikel-brostrom/yolo_tracking/blob/0752c7eaed41183c0ebc8ac8a31044b365817d7c/examples/detectors/strategy/yolonas.py#L13-L16
> 
> to:
> 
> ```python
> self.model = models.get(
>     'yolo_nas_s',
>     num_classes=<the-number-of-classes-in-your-model>,
>     checkpoint_path =<path-to-your-weights.pt>
> )
> ```
> 
> It is impossible for me to infer which YOLONAS model you trained and its number of classes as this is not stored as metadata in the model itself. So you sadly have to configure this yourself @Choneke

Thank you very much for this detailed explanation.

**Comment by mikel-brostrom** [comment]
Unless this is fixed on SuperGradients' side I cannot make the custom model loading in this repo more friendly. THis is already reported here:

https://github.com/Deci-AI/super-gradients/issues/1303

**Comment by Choneke** [comment]
@mikel-brostrom  I followed all the steps, Installed  the latest version of yolo_tracking, then changed yolonas.py from line 13 with the suggested lines. The following lines are changed based on my yolonas trained model, and its path.

```
        self.model = models.get(
            'yolo_nas_s',
            num_classes=1,
            checkpoint_path='D:\yolo_tracking\examples\weights\yolonasweights\yolonass_myweight_EP150.pth'
        ).to(device)

        self.has_run = False  
```

Then I run the following command for evaluation of my custom dataset: 

`python examples/val.py --yolo-model D:\yolo_tracking/examples/weights/yolonasweights/yolonass_myweight_EP150.pth --tracking-method bytetrack --benchmark MOTCUSTOM --split test 
`

However, I got the following error: 


```
2023-07-21 17:32:12.027 | INFO     | __main__:run:66 - {'yolo_model': WindowsPath('D:/yolo_tracking/examples/weights/yolonasweights/yolonass_myweight_EP150.pth'), 'reid_model': WindowsPath('D:/yolo_tracking/examples/weights/mobilenetv2_x1_4_dukemtmcreid.pt'), 'tracking_method': 'bytetrack', 'source': 'D:\yolo_tracking\\examples\\val_utils\\data\\MOTCUSTOM\\test\\V000\\img1', 'imgsz': [1280], 'conf': 0.45, 'iou': 0.7, 'device': '', 'show': False, 'save': True, 'classes': [0], 'project': 'D:\\\yolo_tracking\\examples\\runs\\val', 'name': 'exp3', 'exist_ok': True, 'half': False, 'vid_stride': 1, 'show_labels': True, 'show_conf': True, 'save_txt': False, 'save_id_crops': False, 'save_mot': True, 'line_width': None, 'per_class': False}
Traceback (most recent call last):
  File "D:\yolo_tracking\examples\track.py", line 280, in <module>
Traceback (most recent call last):
  File "D:\yolo_tracking\examples\track.py", line 280, in <module>
    main(opt)
  File "D:\yolo_tracking\examples\track.py", line 275, in main
    main(opt)
  File "D:\yolo_tracking\examples\track.py", line 275, in main
    run(vars(opt))
  File "C:\Users\admin\anaconda3\envs\yolotrackingnew\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    run(vars(opt))
    return func(*args, **kwargs)
  File "D:\yolo_tracking\examples\track.py", line 98, in run
  File "C:\Users\admin\anaconda3\envs\yolotrackingnew\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    yolo_strategy = yolo_strategy(
TypeError: 'NoneType' object is not callable
    return func(*args, **kwargs)
  File "D:\yolo_tracking\examples\track.py", line 98, in run
    yolo_strategy = yolo_strategy(
TypeError: 'NoneType' object is not callable
2023-07-21 17:32:12.603 | SUCCESS  | __main__:eval:215 - Evaluation succeeded
val: yolo_model=D:\yolo_tracking/examples/weights/yolonasweights/yolonass_myweight_EP150.pth, reid_model=D:\yolo_tracking\examples\weights\mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=bytetrack, name=exp, classes=['0'], project=D:\yolo_tracking\examples\runs\val, exist_ok=False, benchmark=MOTCUSTOM, split=test, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
2023-07-21 17:32:13.336 | ERROR    | __main__:eval:245 - Traceback (most recent call last):
  File "D:\yolo_tracking\examples\val_utils\scripts\run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "D:\yolo_tracking\examples\val_utils\trackeval\datasets\mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: labels//V000.txt

2023-07-21 17:32:13.340 | ERROR    | __main__:eval:246 -
Eval Config:
USE_PARALLEL         : True
NUM_PARALLEL_CORES   : 4
BREAK_ON_ERROR       : True
RETURN_ON_ERROR      : False
LOG_ON_ERROR         : D:\yolo_tracking\examples\val_utils\error_log.txt
PRINT_RESULTS        : True
PRINT_ONLY_COMBINED  : False
PRINT_CONFIG         : True
TIME_PROGRESS        : True
DISPLAY_LESS_PROGRESS : False
OUTPUT_SUMMARY       : True
OUTPUT_EMPTY_CLASSES : True
OUTPUT_DETAILED      : True
PLOT_CURVES          : True

MotChallenge2DBox Config:
PRINT_CONFIG         : True
GT_FOLDER            : D:\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test
TRACKERS_FOLDER      : D:\yolo_tracking\examples\runs\val\exp3
OUTPUT_FOLDER        : None
TRACKERS_TO_EVAL     : ['labels']
CLASSES_TO_EVAL      : ['pedestrian']
BENCHMARK            :
SPLIT_TO_EVAL        : train
INPUT_AS_ZIP         : False
DO_PREPROC           : True
TRACKER_SUB_FOLDER   :
OUTPUT_SUB_FOLDER    :
TRACKER_DISPLAY_NAMES : None
SEQMAP_FOLDER        : None
SEQMAP_FILE          : None
SEQ_INFO             : {'V000': None, 'V005': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt
SKIP_SPLIT_FOL       : True
Tracker file not found: D:\yolo_tracking\examples\runs\val\exp3\labels\V000.txt
```

But, when I use other detector it works fine.

Can you help to resolve it?

**Comment by mikel-brostrom** [comment]
Run this:

`python examples/val.py --yolo-model yolo_nas_s --tracking-method bytetrack --benchmark MOTCUSTOM --split test `

This is correct:

```
 
self.model = models.get(
            'yolo_nas_s',
            num_classes=1,
            checkpoint_path='D:\yolo_tracking\examples\weights\yolonasweights\yolonass_myweight_EP150.pth'
        ).to(device)
```

Let me know if it works :smile:

**Comment by Choneke** [comment]
Thank you @mikel-brostrom .  Now It works fine. 
One more, question, is it possible to change the class name, because on the displayed when show tracking, it show track ID and the class name (person), instead of the name of the class in the dataset that  model are trained.

**Comment by mikel-brostrom** [comment]
Sorry, forgot to respond to this @Choneke. It is not possible, we use the Yolov8 backend for all plotting and this feature is not in there so cannot do much about it

**Comment by Choneke** [comment]
Thank you @mikel-brostrom
