### ISSUE TITLE
File MOT17-02-FRCNN.txt cannot be read because it is either not present or invalidly formatted

### ISSUE THREAD

**Issue by Jumabek** [mikel-brostrom/yolo_tracking#1011]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evaluation

### Bug

Issue is happening when `yolox_n.pt` is selected

command to reproduce

 `python3 examples/val.py  --yolo-model yolox_n.pt     --tracking-method ocsort     --benchmark MOT17-mini`

Sample error messages
(myenv) juma@juma-System-Product-Name:~/code/luqmon_tracking$ python3 examples/val.py  --yolo-model yolox_n.pt     --tracking-method ocsort     --benchmark MOT17-mini
FILE: /home/juma/code/luqmon_tracking/boxmot/utils/__init__.py
ROOT: /home/juma/code/luqmon_tracking
BOXMOT: /home/juma/code/luqmon_tracking/boxmot
EXAMPLES: /home/juma/code/luqmon_tracking/examples
WEIGHTS: /home/juma/code/luqmon_tracking/examples/weights
REQUIREMENTS: /home/juma/code/luqmon_tracking/requirements.txt
val: yolo_model=yolox_n.pt, reid_model=/home/juma/code/luqmon_tracking/examples/weights/mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=ocsort, name=exp, classes=['0'], project=/home/juma/code/luqmon_tracking/examples/runs/val, exist_ok=False, benchmark=MOT17-mini, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
2023-07-21 14:20:51.772 | INFO     | __main__:download_mot_eval_tools:65 - Eval repo already downloaded
seq_paths [PosixPath('/home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-02-FRCNN/img1'), PosixPath('/home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-13-FRCNN/img1'), PosixPath('/home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-05-FRCNN/img1'), PosixPath('/home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-09-FRCNN/img1'), PosixPath('/home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-11-FRCNN/img1'), PosixPath('/home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-10-FRCNN/img1'), PosixPath('/home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-04-FRCNN/img1')] save_dir /home/juma/code/luqmon_tracking/examples/runs/val/exp6 /home/juma/code/luqmon_tracking/examples/val_utils/data/trackers/mot_challenge/MOT17-mini/exp6/data /home/juma/code/luqmon_tracking/assets/MOT17-mini/train
2023-07-21 14:20:51.772 | INFO     | __main__:eval:186 - Staring evaluation process on /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-02-FRCNN/MOT17-02-FRCNN
2023-07-21 14:21:54.539 | SUCCESS  | __main__:eval:218 - /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-02-FRCNN/MOT17-02-FRCNN evaluation succeeded
2023-07-21 14:21:54.540 | INFO     | __main__:eval:186 - Staring evaluation process on /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-13-FRCNN/MOT17-13-FRCNN
2023-07-21 14:23:06.063 | SUCCESS  | __main__:eval:218 - /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-13-FRCNN/MOT17-13-FRCNN evaluation succeeded
2023-07-21 14:23:06.063 | INFO     | __main__:eval:186 - Staring evaluation process on /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN
2023-07-21 14:24:21.491 | SUCCESS  | __main__:eval:218 - /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN evaluation succeeded
2023-07-21 14:24:21.491 | INFO     | __main__:eval:186 - Staring evaluation process on /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-09-FRCNN/MOT17-09-FRCNN
2023-07-21 14:25:43.588 | SUCCESS  | __main__:eval:218 - /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-09-FRCNN/MOT17-09-FRCNN evaluation succeeded
2023-07-21 14:25:43.589 | INFO     | __main__:eval:186 - Staring evaluation process on /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-11-FRCNN/MOT17-11-FRCNN
2023-07-21 14:26:39.536 | SUCCESS  | __main__:eval:218 - /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-11-FRCNN/MOT17-11-FRCNN evaluation succeeded
2023-07-21 14:26:39.536 | INFO     | __main__:eval:186 - Staring evaluation process on /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-10-FRCNN/MOT17-10-FRCNN
2023-07-21 14:27:51.184 | SUCCESS  | __main__:eval:218 - /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-10-FRCNN/MOT17-10-FRCNN evaluation succeeded
2023-07-21 14:27:51.184 | INFO     | __main__:eval:186 - Staring evaluation process on /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-04-FRCNN/MOT17-04-FRCNN
2023-07-21 14:29:29.653 | SUCCESS  | __main__:eval:218 - /home/juma/code/luqmon_tracking/assets/MOT17-mini/train/MOT17-04-FRCNN/MOT17-04-FRCNN evaluation succeeded
val: yolo_model=yolox_n.pt, reid_model=/home/juma/code/luqmon_tracking/examples/weights/mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=ocsort, name=exp, classes=['0'], project=/home/juma/code/luqmon_tracking/examples/runs/val, exist_ok=False, benchmark=MOT17-mini, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
2023-07-21 14:29:29.871 | ERROR    | __main__:eval:251 - Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 152, in _load_simple_text_file
    fp = open(file)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 152, in _load_simple_text_file
    fp = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-02-FRCNN.txt'
FileNotFoundError: [Errno 2] No such file or directory: '/home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-09-FRCNN.txt'
Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 152, in _load_simple_text_file
    fp = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-13-FRCNN.txt'
Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 152, in _load_simple_text_file
    fp = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-05-FRCNN.txt'
Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 152, in _load_simple_text_file
    fp = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-10-FRCNN.txt'
Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 152, in _load_simple_text_file
    fp = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-11-FRCNN.txt'
Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 152, in _load_simple_text_file
    fp = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-04-FRCNN.txt'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 152, in _load_simple_text_file
    fp = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-02-FRCNN.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/eval.py", line 218, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 93, in get_raw_seq_data
    raw_tracker_data = self._load_raw_file(tracker, seq, is_gt=False)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 240, in _load_raw_file
    read_data, ignore_data = self._load_simple_text_file(
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 209, in _load_simple_text_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: File MOT17-02-FRCNN.txt cannot be read because it is either not present or invalidly formatted
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/eval.py", line 102, in evaluate
    results = pool.map(_eval_sequence, seq_list)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
trackeval.utils.TrackEvalException: File MOT17-02-FRCNN.txt cannot be read because it is either not present or invalidly formatted
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 152, in _load_simple_text_file
    fp = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-02-FRCNN.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/eval.py", line 218, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 93, in get_raw_seq_data
    raw_tracker_data = self._load_raw_file(tracker, seq, is_gt=False)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 240, in _load_raw_file
    read_data, ignore_data = self._load_simple_text_file(
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/datasets/_base_dataset.py", line 209, in _load_simple_text_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: File MOT17-02-FRCNN.txt cannot be read because it is either not present or invalidly formatted
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/juma/code/luqmon_tracking/examples/val_utils/scripts/run_mot_challenge.py", line 99, in <module>
    evaluator.evaluate(dataset_list, metrics_list)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/eval.py", line 207, in evaluate
    raise err
  File "/home/juma/code/luqmon_tracking/examples/val_utils/trackeval/eval.py", line 102, in evaluate
    results = pool.map(_eval_sequence, seq_list)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
trackeval.utils.TrackEvalException: File MOT17-02-FRCNN.txt cannot be read because it is either not present or invalidly formatted

2023-07-21 14:29:29.871 | ERROR    | __main__:eval:252 - 
Eval Config:
USE_PARALLEL         : True                          
NUM_PARALLEL_CORES   : 4                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /home/juma/code/luqmon_tracking/examples/val_utils/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          
Running evaluation with config: {'PRINT_CONFIG': True, 'GT_FOLDER': '/home/juma/code/luqmon_tracking/assets/MOT17-mini/train', 'TRACKERS_FOLDER': '/home/juma/code/luqmon_tracking/examples/runs/val/exp6', 'OUTPUT_FOLDER': None, 'TRACKERS_TO_EVAL': ['labels'], 'CLASSES_TO_EVAL': ['pedestrian'], 'BENCHMARK': '', 'SPLIT_TO_EVAL': 'train', 'INPUT_AS_ZIP': False, 'DO_PREPROC': True, 'TRACKER_SUB_FOLDER': '', 'OUTPUT_SUB_FOLDER': '', 'TRACKER_DISPLAY_NAMES': None, 'SEQMAP_FOLDER': None, 'SEQMAP_FILE': None, 'SEQ_INFO': {'MOT17-02-FRCNN': None, 'MOT17-13-FRCNN': None, 'MOT17-05-FRCNN': None, 'MOT17-09-FRCNN': None, 'MOT17-11-FRCNN': None, 'MOT17-10-FRCNN': None, 'MOT17-04-FRCNN': None}, 'GT_LOC_FORMAT': '{gt_folder}/{seq}/gt/gt.txt', 'SKIP_SPLIT_FOL': True}

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /home/juma/code/luqmon_tracking/assets/MOT17-mini/train
TRACKERS_FOLDER      : /home/juma/code/luqmon_tracking/examples/runs/val/exp6
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['labels']                    
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            :                               
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   :                               
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : {'MOT17-02-FRCNN': None, 'MOT17-13-FRCNN': None, 'MOT17-05-FRCNN': None, 'MOT17-09-FRCNN': None, 'MOT17-11-FRCNN': None, 'MOT17-10-FRCNN': None, 'MOT17-04-FRCNN': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : True                          

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity'] 
THRESHOLD            : 0.5                           
PRINT_CONFIG         : True                          

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity'] 
THRESHOLD            : 0.5                           
PRINT_CONFIG         : True                          

Evaluating 1 tracker(s) on 7 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count

Evaluating labels

Error loading file: /home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-05-FRCNN.txt, printing traceback.
Error loading file: /home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-09-FRCNN.txt, printing traceback.
Error loading file: /home/juma/code/luqmon_tracking/examples/runs/val/exp6/labels/MOT17-10-FRCNN.txt, printing traceback.
Tracker labels was unable to be evaluated.
File MOT17-02-FRCNN.txt cannot be read because it is either not present or invalidly formatted

### Environment

Ubuntu2022.04

3090 GTX GPU

### Minimal Reproducible Example

```
python3 examples/val.py  --yolo-model yolox_n.pt     --tracking-method ocsort     --benchmark MOT17-mini
```

**Comment by mikel-brostrom** [comment]
yolox_n.pt should be  yolox_n 

```
python3 examples/val.py  --yolo-model yolox_n --tracking-method ocsort --benchmark MOT17-mini
```
