### ISSUE TITLE
I am getting an error when trying to convert mobilenetv2_1.0-0f96a698.pth  to onnx using the reid_export.py

### ISSUE THREAD

**Issue by dinushazoomi** [mikel-brostrom/yolo_tracking#1021]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

steps to reproduce:
1. download the image net trained weights from this link : https://drive.google.com/file/d/1K7_CZE_L_Tf-BRY6_vVm0G-0ZKjVWh3R/view?usp=sharing (from the [model zoo](https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO))
2. run `python3 reid_export.py --include onnx --weights ./mobilenetv2_1.0-0f96a698.pth --device 0` in `boxmot/deep` folder.

Error message:
```
2023-07-26 03:56:53.576 | INFO     | boxmot.utils.torch_utils:select_device:52 - Yolo Tracking v10.0.14 🚀 Python-3.8.10 torch-1.11.0 CUDA:0 (Orin, 30536MiB)

Traceback (most recent call last):
  File "reid_export.py", line 242, in <module>
    model = build_model(
  File "/usr/local/lib/python3.8/dist-packages/boxmot/deep/models/__init__.py", line 116, in build_model
    raise KeyError(
KeyError: "Unknown model: None. Must be one of ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d', 'resnext101_32x8d', 'resnet50_fc512', 'se_resnet50', 'se_resnet50_fc512', 'se_resnet101', 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'densenet121_fc512', 'inceptionresnetv2', 'inceptionv4', 'xception', 'resnet50_ibn_a', 'resnet50_ibn_b', 'nasnsetmobile', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4', 'shufflenet', 'squeezenet1_0', 'squeezenet1_0_fc512', 'squeezenet1_1', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'mudeep', 'resnet50mid', 'hacnn', 'pcb_p6', 'pcb_p4', 'mlfn', 'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25', 'osnet_ibn_x1_0', 'osnet_ain_x1_0', 'osnet_ain_x0_75', 'osnet_ain_x0_5', 'osnet_ain_x0_25', 'lmbn_n']"

```
Any help would be highly appreciated.
Thanks

**Comment by mikel-brostrom** [comment]
As you are not downloading the ReID weight using this repo you are getting name formatting problems. Change `./mobilenetv2_1.0-0f96a698.pth` to `./mobilenetv2_x1_imagenet.pt`
