### ISSUE TITLE
ModuleNotFoundError: No module named 'boxmot.appearance.backbones.lmbn'

### ISSUE THREAD

**Issue by JazzyPascal** [mikel-brostrom/yolo_tracking#1060]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

Traceback (most recent call last):
  File "/content/yolo_tracking/examples/track.py", line 9, in <module>
    from boxmot import TRACKERS
  File "/usr/local/lib/python3.10/dist-packages/boxmot/__init__.py", line 7, in <module>
    from boxmot.trackers.botsort.bot_sort import BoTSORT
  File "/usr/local/lib/python3.10/dist-packages/boxmot/trackers/botsort/bot_sort.py", line 8, in <module>
    from boxmot.appearance.reid_multibackend import ReIDDetectMultiBackend
  File "/usr/local/lib/python3.10/dist-packages/boxmot/appearance/reid_multibackend.py", line 13, in <module>
    from boxmot.appearance.backbones import build_model
  File "/usr/local/lib/python3.10/dist-packages/boxmot/appearance/backbones/__init__.py", line 7, in <module>
    from boxmot.appearance.backbones.lmbn.lmbn_n import LMBN_n
ModuleNotFoundError: No module named 'boxmot.appearance.backbones.lmbn'

It worked the first time I ran it, then...now this is the output

### Environment

google-colab

### Minimal Reproducible Example

!python examples/track.py --yolo-model yolov8n.pt --reid-model osnet_x0_25_msmt17.pt --source out.avi --save --conf 0.2

**Comment by mikel-brostrom** [comment]
A lot of things are changing in the repo. Please start from a clean slate to be sure that it works as expected. Reinstall the environment as well.

**Comment by mikel-brostrom** [comment]
I have no problem running this on my side:

```
python examples/track.py --yolo-model yolov8n.pt --reid-model osnet_x0_25_msmt17.pt --source out.avi --save --conf 0.2 

2023-08-08 13:57:10.286 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:207 - Successfully loaded pretrained weights from "osnet_x0_25_msmt17.pt"
2023-08-08 13:57:10.286 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:211 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')
[ERROR:0@8.885] global cap.cpp:643 open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.8.0) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /home/mikel.brostrom/yolo_tracking/examples/runs/track/exp/out.avi in function 'icvExtractPattern'


video 1/1 (1/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 27 persons, 1 car, 1 motorcycle, 1 backpack, 32.8ms
video 1/1 (2/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 26 persons, 1 car, 1 motorcycle, 1 backpack, 25.0ms
video 1/1 (3/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 24 persons, 1 car, 1 motorcycle, 16.3ms
video 1/1 (4/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 24 persons, 1 car, 1 motorcycle, 17.6ms
video 1/1 (5/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 24 persons, 1 car, 1 motorcycle, 16.8ms
video 1/1 (6/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 25 persons, 1 car, 1 motorcycle, 15.1ms
video 1/1 (7/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 25 persons, 1 car, 1 motorcycle, 16.8ms
video 1/1 (8/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 26 persons, 1 car, 1 motorcycle, 1 backpack, 1 potted plant, 17.9ms
video 1/1 (9/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 26 persons, 1 car, 1 motorcycle, 1 backpack, 1 potted plant, 16.4ms
video 1/1 (10/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 25 persons, 1 car, 1 motorcycle, 1 backpack, 1 potted plant, 16.0ms
video 1/1 (11/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 24 persons, 1 car, 2 motorcycles, 1 potted plant, 21.5ms
video 1/1 (12/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 24 persons, 1 car, 2 motorcycles, 1 potted plant, 16.9ms
video 1/1 (13/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 25 persons, 1 car, 1 motorcycle, 17.3ms
video 1/1 (14/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 24 persons, 1 car, 1 motorcycle, 16.9ms
video 1/1 (15/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 25 persons, 1 car, 1 motorcycle, 17.8ms
video 1/1 (16/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 24 persons, 1 car, 2 motorcycles, 17.4ms
video 1/1 (17/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 22 persons, 1 car, 2 motorcycles, 17.7ms
video 1/1 (18/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 22 persons, 1 car, 1 motorcycle, 16.1ms
video 1/1 (19/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 23 persons, 1 car, 1 motorcycle, 18.0ms
video 1/1 (20/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 23 persons, 1 bicycle, 1 car, 1 motorcycle, 16.9ms
video 1/1 (21/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 24 persons, 1 car, 1 motorcycle, 17.5ms
video 1/1 (22/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 24 persons, 1 car, 2 motorcycles, 17.4ms
video 1/1 (23/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 23 persons, 1 car, 2 motorcycles, 19.0ms
video 1/1 (24/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 22 persons, 1 car, 1 motorcycle, 18.2ms
video 1/1 (25/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 20 persons, 1 car, 17.2ms
video 1/1 (26/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 21 persons, 1 car, 18.5ms
video 1/1 (27/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 21 persons, 1 car, 16.6ms
video 1/1 (28/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 21 persons, 1 car, 17.3ms
video 1/1 (29/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 23 persons, 1 car, 16.8ms
video 1/1 (30/30) /home/mikel.brostrom/yolo_tracking/out.avi: 384x640 21 persons, 1 car, 17.4ms
Speed: 3.2ms preprocess, 18.1ms inference, 3.0ms postprocess, 98.4ms tracking per image at shape (1, 3, 384, 640)
Results saved to /home/mikel.brostrom/yolo_tracking/examples/runs/track/exp
```

**Comment by mikel-brostrom** [comment]
Ahaa, it is on colab. Will check that out :smile:

**Comment by mikel-brostrom** [comment]
Found a bug. No related to [this](https://github.com/mikel-brostrom/yolo_tracking/issues/1060#issue-1841143712) though.
