### ISSUE TITLE
'Custom object detection model example' not working?

### ISSUE THREAD

**Issue by zhuolisam** [mikel-brostrom/yolo_tracking#1083]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I'm trying to port DeepOCSort into RTMDetector, I'm referring to your Custom object detection model example in the README.

```
import cv2
import numpy as np
from pathlib import Path

from boxmot import DeepOCSORT, OCSORT, StrongSORT, BYTETracker, BoTSORT
from rtm.detectors import get_detector

tracker = DeepOCSORT(
    model_weights=Path("osnet_x0_25_msmt17.pt"),  # which ReID model to use
    device="cuda:0",
    fp16=True,
)

detector = get_detector(
    "rtmdet-m",
    device="cuda",
) #my own zoo function that returns the Detector

vid = cv2.VideoCapture("data/Men 100m/Men 100m Heat-1.mp4")
color = (0, 0, 255)  # BGR
thickness = 2
fontscale = 0.5

while True:
    ret, im = vid.read()

    # substitute by your object detector, input to tracker has to be N X (x, y, x, y, conf, cls)
    # dets = detector(im)  # --> (x, y, x, y, conf, cls
    detections = detector(im)
    bboxes, scores, labels = (
        detections.xyxy,
        detections.confidence,
        detections.labels,
    )
    print(
        len(bboxes),
        len(scores),
        len(labels),
    ) 

    raw_detections = []
    for x1, y1, x2, y2, conf, cls in zip(
        bboxes[:, 0],
        bboxes[:, 1],
        bboxes[:, 2],
        bboxes[:, 3],
        scores,
        labels,
    ):
        raw_detections.append([x1, y1, x2, y2, conf, cls])
    raw_detections = np.array(raw_detections)
    tracks = tracker.update(raw_detections, im)  # --> (x, y, x, y, id, conf, cls, ind)

    # in case you have segmentations or poses alongside with your detections you can use
    # the ind variable in order to identify which track is associated to each seg or pose by:
    # segs = segs[inds]
    # poses = poses[inds]
    # you can then zip them together: zip(tracks, poses)

    # print bboxes with their associated id, cls and conf
    if tracks.shape[0] != 0:
        xyxys = tracks[:, 0:4].astype("int")  # float64 to int
        ids = tracks[:, 4].astype("int")  # float64 to int
        confs = tracks[:, 5]
        clss = tracks[:, 6].astype("int")  # float64 to int
        inds = tracks[:, 7].astype("int")  # float64 to int
        for xyxy, id, conf, cls in zip(xyxys, ids, confs, clss):
            im = cv2.rectangle(
                im, (xyxy[0], xyxy[1]), (xyxy[2], xyxy[3]), color, thickness
            )
            cv2.putText(
                im,
                f"id: {id}, conf: {conf}, c: {cls}",
                (xyxy[0], xyxy[1] - 10),
                cv2.FONT_HERSHEY_SIMPLEX,
                fontscale,
                color,
                thickness,
            )

    # show image with bboxes, ids, classes and confidences
    cv2.imshow("frame", im)

    # break on pressing q
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

vid.release()
cv2.destroyAllWindows()
```

However, I got this error,
```
Traceback (most recent call last):
  File "C:\Users\zhuol\OneDrive - Universiti Malaya\Documents\zl\CS Sem 6 Resource\FYP\rtm\test_yolo_tracking.py", line 52, in <module>
    tracks = tracker.update(raw_detections, im)  # --> (x, y, x, y, id, conf, cls, ind)       
  File "C:\Users\zhuol\anaconda3\envs\rtm\lib\site-packages\boxmot\utils\__init__.py", line 55, in wrapper
    mc_dets = np.append(mc_dets, dets, axis=0)
  File "<__array_function__ internals>", line 180, in append
  File "C:\Users\zhuol\anaconda3\envs\rtm\lib\site-packages\numpy\lib\function_base.py", line 
5444, in append
    return concatenate((arr, values), axis=axis)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but 
along dimension 1, the array at index 0 has size 7 and the array at index 1 has size 8 
```

Would you happen to have any idea? 

Also, the reason I'm using a tracker is to get more stable human detection results across all frames. Sometimes the detector does not detect the person in between frames
```
frame 1   -   frame 2   - frame 3
detected - not detected - detected 
                  ^
      not detecting altho subject is there
```

The detection results would be used in the next stage's pose estimator.

The pipeline would be input frame -> human detector -> tracker -> pose estimator. I thought that the tracker would fix missing detection in-between frames by tracking the human subject, hence stable detection results can be obtained. Is this approach feasible? Appreciate your input I'm just a beginner in this.

**Comment by mikel-brostrom** [comment]
What is the input shape (raw_detections) to the tracker?

**Comment by mikel-brostrom** [comment]
Yup, can reproduce. Working on it.

**Comment by mikel-brostrom** [comment]
Try:

```py
tracker = DeepOCSORT(
    model_weights=Path("osnet_x0_25_msmt17.pt"),  # which ReID model to use
    device="cuda:0",
    fp16=True,
    per_class=False
)
```

**Comment by mikel-brostrom** [comment]
Does it work for you @zhuolisam ?

**Comment by zhuolisam** [comment]
Yep, it's working in the first few frames. But another resize error was thrown after a few frames. This happens to DeepOCSORT and StrongSORT
```Traceback (most recent call last):
  File "C:\Users\zhuol\OneDrive - Universiti Malaya\Documents\zl\CS Sem 6 Resource\FYP\rtm\test_yolo_tracking.py", line 48, in <module>
    tracks = tracker.update(raw_detections, im)  # --> (x, y, x, y, id, conf, cls, ind)       
  File "C:\Users\zhuol\anaconda3\envs\rtm\lib\site-packages\boxmot\utils\__init__.py", line 58, in wrapper
    mc_dets = self.update(instance, dets, im)
  File "C:\Users\zhuol\anaconda3\envs\rtm\lib\site-packages\boxmot\trackers\deepocsort\deep_ocsort.py", line 388, in update
    dets_embs = self.model.get_features(dets[:, :4], img)
  File "C:\Users\zhuol\anaconda3\envs\rtm\lib\site-packages\torch\utils\_contextlib.py", line 
115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\zhuol\anaconda3\envs\rtm\lib\site-packages\boxmot\appearance\reid_multibackend.py", line 300, in get_features
    crops = self.preprocess(xyxys, img)
  File "C:\Users\zhuol\anaconda3\envs\rtm\lib\site-packages\boxmot\appearance\reid_multibackend.py", line 195, in preprocess
    crop = cv2.resize(
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```




I encounter this error when using BoTSORT
```
tracker = BoTSORT(
    model_weights=Path("osnet_x0_25_msmt17.pt"),  # which ReID model to use
    device="cuda:0",
    fp16=True,
)
```

```
Traceback (most recent call last):
  File "C:\Users\zhuol\OneDrive - Universiti Malaya\Documents\zl\CS Sem 6 Resource\FYP\rtm\test_yolo_tracking.py", line 47, in <module>
    tracks = tracker.update(raw_detections, im)  # --> (x, y, x, y, id, conf, cls, ind)       
  File "C:\Users\zhuol\anaconda3\envs\rtm\lib\site-packages\boxmot\trackers\botsort\bot_sort.py", line 316, in update
    dets_second = dets[inds_second]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 24
```


OCSORT and BYTETracker are fine.

**Comment by mikel-brostrom** [comment]
Pull and try again? I have it working on all trackers. Both with `--per-class` and without

**Comment by zhuolisam** [comment]
I still getting errors after pulling, I may need to pip install again, I will get back to you later.

**Comment by zhuolisam** [comment]
> We do not provide multiple predictions ahead at the moment

What I don't understand is this? In object tracking, doesn't the tracker helps when the object detector fails to detect subject on a particular frame? 

Example: 
1. There are two people in the video. In the first frame, object detector produces bboxes for both person A and person B.
2. In the second frame, object detector only produces bboxes for person A (but person B is actually there). 

Shouldn't an object tracker help to predict person B's movement? It helps to recover bboxes of person B and we get both boxes in the end.

**Comment by mikel-brostrom** [comment]
> Shouldn't an object tracker help to predict person B's movement?

The bbox Kalman FIlter predictions have to be associated with an incoming detector bbox. The current implementations only make Kalman FIlter prediction whenever these associations are successful. So while it is true that the tracker could make more than a single prediction ahead in the case that detection bboxes are missing or the association process fails, this is not implemented at the moment.

**Comment by zhuolisam** [comment]
Hey mikel, sorry I was away from the project for some time, anyways thanks a lot for your effort and the explanation, it's working now. I have just one more question: Can the tracker implemented in Ultralytics/YOLO make predictions + update ahead? I noticed you have similar code.

**Comment by mikel-brostrom** [comment]
> Can the tracker implemented in ultralytics/yolo make predictions + update ahead?

As of today, the Ultralytics implementation have no ReID model option. Otherwise they should be fairly similar. Moreover, the tracking modules in this repo can be plugged onto any object detector, segmenation or pose estimation model

**Comment by zhuolisam** [comment]
Cool, thanks for the explanation!

**Comment by mhoare** [comment]
> I am getting an issue here when using default settings on 4k footage? Works fine with 1080p

I actually have found that this error only happens with device set to `mps` on a mac with m1

**Comment by mikel-brostrom** [comment]
Could be a memory issue? Please post the complete output @mhoare, :smile:

**Comment by mhoare** [comment]
Will do - trying to replicate since updating to mac os 13
