### ISSUE TITLE
Cant run my yolox model trained on custom dataset

### ISSUE THREAD

**Issue by NaifahNurya** [mikel-brostrom/yolo_tracking#1092]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I use the following command to run my yolox model trained on custom dataset "python examples/evolve.py --yolo-model H:\yolo_tracking/examples/weights/yolox_best.pth --tracking-method bytetrack --benchmark MOTCUSTOM --split test" to evolve the model. However, I got the following error:

```
Traceback (most recent call last):
  File "H:\tracking\yolo_tracking2\yolo_tracking\examples\track.py", line 280, in <module>
    main(opt)
  File "H:\tracking\yolo_tracking2\yolo_tracking\examples\track.py", line 275, in main
    run(vars(opt))
  File "H:\Users\admin\anaconda3\envs\yolotracking4\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\tracking\yolo_tracking2\yolo_tracking\examples\track.py", line 99, in run
    model = Yolo(
  File "H:\tracking\yolo_tracking2\yolo_tracking\examples\detectors\yolox.py", line 62, in __init__
    exp = get_exp(None, model_type)
  File "H:\Users\IDB\anaconda3\envs\yolotracking4\lib\site-packages\yolox\exp\build.py", line 36, in get_exp
    assert (
AssertionError: plz provide exp file or exp name.
```
Any help to solve the issue, which exp should be provided? For the other detector it run successful, only yolox provide an error

**Comment by mikel-brostrom** [comment]
You model names has to contain one of: 'yolox_n', 'yolox_s', 'yolox_m', 'yolox_l', 'yolox_x'. See:

https://github.com/mikel-brostrom/yolo_tracking/blob/287788a6a888c2d566260531cec9b086f206e202/examples/detectors/yolox.py#L54-L55

**Comment by NaifahNurya** [comment]
Thank you @mikel-brostrom , the issue solved.
