### ISSUE TITLE
No module named 'examples.detectors'

### ISSUE THREAD

**Issue by rknetwork** [mikel-brostrom/yolo_tracking#1093]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I installed all packages from requirements.txt:
`pip install -r requirements.txt`

But when I'm trying to run:
`python examples/track.py --yolo-model yolov8n --tracking-method deepocsort --source 0`

I'm getting this error:

```
from examples.detectors import get_yolo_inferer
ModuleNotFoundError: No module named 'examples.detectors'
```
Did I miss anything?

**Comment by mikel-brostrom** [comment]
Just copypasting from the README:

> If you want to run the YOLOv8, YOLO-NAS or YOLOX examples:
> 
> git clone https://github.com/mikel-brostrom/yolo_tracking.git
> pip install -v -e .

**Comment by fatbringer** [comment]
Hey @mikel-brostrom  i did just that, and i got this error
```
Using pip 23.2.1 from /home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/pip (python 3.9)
Obtaining file:///home/aevas/Desktop/Tracking_algos
ERROR: file:///home/aevas/Desktop/Tracking_algos does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
This can be overcome by cd-ing into the cloned folder, and then i ran ```pip install -v -e .```
Which gave me that boxmot is successfully installed
```
Installing collected packages: boxmot
  Attempting uninstall: boxmot
    Found existing installation: boxmot 10.0.42
    Uninstalling boxmot-10.0.42:
      Removing file or directory /home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/boxmot.egg-link
      Removing pth entries from /home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/easy-install.pth:
      Removing entry: /home/aevas/Desktop/Tracking_algos/yoloV8_tracking_mikel-brostrom
      Successfully uninstalled boxmot-10.0.42
  Running setup.py develop for boxmot
    Running command python setup.py develop
    running develop
    running egg_info
    creating boxmot.egg-info
    writing boxmot.egg-info/PKG-INFO
    writing dependency_links to boxmot.egg-info/dependency_links.txt
    writing requirements to boxmot.egg-info/requires.txt
    writing top-level names to boxmot.egg-info/top_level.txt
    writing manifest file 'boxmot.egg-info/SOURCES.txt'
    reading manifest file 'boxmot.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory '__pycache__'
    adding license file 'LICENSE'
    writing manifest file 'boxmot.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/boxmot.egg-link (link to .)
    Adding boxmot 10.0.42 to easy-install.pth file

    Installed /home/aevas/Desktop/Tracking_algos/yolo_tracking
Successfully installed boxmot-10.0.42
```

However, i still got the same error
```
python examples/track.py --yolo-model yolov8n --tracking-method deepocsort --source 0
Traceback (most recent call last):
  File "/home/aevas/Desktop/Tracking_algos/yolo_tracking/examples/track.py", line 13, in <module>
    from examples.detectors import get_yolo_inferer
ModuleNotFoundError: No module named 'examples.detectors'
``` 

Any idea why?

**Comment by rknetwork** [comment]
> Any idea why?
Just because developer is an idiot?

**Comment by mikel-brostrom** [comment]
If you run:

```bash
git clone https://github.com/mikel-brostrom/yolo_tracking.git
cd yolo_tracking/boxmot
pip install -v -e .
```

Then you need to:

```bash
cd ..`
```

in order to run:

```bash
 python examples/track.py --yolo-model yolov8n --tracking-method deepocsort --source 0
```

The path in the command above is relative to you current one

**Comment by fatbringer** [comment]
@mikel-brostrom  Yup i understand that it is relative. But  now i got something more peculiar. So i recloned the repo as follows. 

```
git clone https://github.com/mikel-brostrom/yolo_tracking.git
cd yolo_tracking/boxmot
pip install -v -e .
Using pip 23.2.1 from /home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/pip (python 3.9)
Obtaining file:///home/aevas/Desktop/Tracking_algos/yolo_tracking/boxmot
ERROR: file:///home/aevas/Desktop/Tracking_algos/yolo_tracking/boxmot does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

The setup.py file is outside of the boxmot folder though. Should it be inside?

**Comment by mikel-brostrom** [comment]
Sorry. Should be: 

```bash
git clone https://github.com/mikel-brostrom/yolo_tracking.git
cd yolo_tracking
pip install -v -e .
```

**Comment by fatbringer** [comment]
Ok i did just that. Now i am back to the same error
```
python examples/track.py --yolo-model yolov8n --tracking-method deepocsort --source 0
Traceback (most recent call last):
  File "/home/aevas/Desktop/Tracking_algos/yolo_tracking/examples/track.py", line 13, in <module>
    from examples.detectors import get_yolo_inferer
ModuleNotFoundError: No module named 'examples.detectors'
```

Could i be missing any libraries or something?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/issues/1093#issuecomment-1704703085

**Comment by fatbringer** [comment]
I have now gotten another error related to ultralytics
```
python examples/track.py --yolo-model yolov8n --tracking-method deepocsort --source 0
Traceback (most recent call last):
  File "/home/aevas/Desktop/Tracking_algos/yolo_tracking/examples/track.py", line 19, in <module>
    from ultralytics.data.utils import VID_FORMATS
ModuleNotFoundError: No module named 'ultralytics.data'
```
I have already performed ```pip install ultralytics``` in the past because i had tried to use yolov8.

**Comment by mikel-brostrom** [comment]
You cannot install whatever version of a pip package you want and expect a repo to work with it. Why? Imports change, functionality change... that the repo may be dependent on. We have a pinned custom Ultralytics package. That is why you get  all these errors. Long story short, start from scratch:

1. Create a new empty pip environment (ONLY for this project)
2. Follow the README
