### ISSUE TITLE
val.py , Error: "tracker file not found:mot//MOT17-02-FRCNN.txt" .

### ISSUE THREAD

**Issue by chenke225** [mikel-brostrom/yolo_tracking#1140]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evaluation

### Bug

Run val.py to evaluate the tracker's MOT17 performance.
Entering the val.py parameter, if chose --save (save video tracking results),  an error occurs when running val.py.
The mot results cannot be found, that is, there are only labels and video frame images in the yolo_tracking\runs\val\exp?\ directory. Possibly, one of "--save" and "--save-mot" in args can be choice. 
See def evl(), p=subprocess.Popen( arge[ [
               "--save" if self.opt.save else"" "--save-mot",

If "--save" is specified, an error will occur when running val.py and mot_challenge2DBox.py. Error:  "tracker file not found:mot//MOT17-02-FRCNN.txt" .
In fact, saving video tracking results is meaningless, because "--save" only saves the tracking video of the last sequence in the MOT17 sequence, and the tracking video of the previous sequence is overwritten.

### Environment

Yolo Tracking v10.0.43, Python-3.8.16 torch-2.0.1 cpu only.

### Minimal Reproducible Example

```
def eval(self, opt, seq_paths, save_dir, MOT_results_folder, val_tools_path, gt_folder, free_devices):
   ... 
   if not self.opt.eval_existing:
            processes = []

            busy_devices = []

            for i, seq_path in enumerate(seq_paths):
                ...  
                p = subprocess.Popen(
                    args=[
                        sys.executable, str(EXAMPLES / "track.py"),
                        "--yolo-model", self.opt.yolo_model,
                        "--reid-model", self.opt.reid_model,
                        "--tracking-method", self.opt.tracking_method,
                        "--conf", str(self.opt.conf),
                        "--imgsz", str(self.opt.imgsz[0]),
                        "--classes", *self.opt.classes,
                        "--name", save_dir.name,
                        "--save" if self.opt.save else ""
                        "--save-mot",
                        "--project", self.opt.project,
                        "--device", str(tracking_subprocess_device),
                        "--source", seq_path,
                        "--exist-ok",
                    ],

**Comment by mikel-brostrom** [comment]
Please provide the FULL error logs. I cannot help you otherwise

**Comment by datct00** [comment]
I have a similar error as him. I am using DanceTrack dataset to evaluate BoT-SORT, OC-SORT and StrongSORT with YOLOX_N and osnet_ain_x1_0_msmt17 as detector and reid model respectively. 

My DanceTrack dataset structure: 
yolo_tracking
├── examples
│   ├── val_utils 
│   │   ├── data
│   │   │    ├──dancetrack


My command to evaluate Deep OC-SORT:
```
python3 examples/val.py --yolo-model yolox_n.pt --reid-model osnet_ain_x1_0_msmt17.pt --tracking-method deepocsort --benchmark dancetrack --save --device 0 --split val
``` 

My error logs: 

> 2023-10-06 11:02:34.972 | INFO     | __main__:eval:195 - Staring evaluation process on /workspace/yolo_tracking/examples/val_utils/data/dancetrack/train/dancetrack0029/img1
2023-10-06 11:02:35.123 | INFO     | __main__:eval:195 - Staring evaluation process on /workspace/yolo_tracking/examples/val_utils/data/dancetrack/train/dancetrack0062/img1
2023-10-06 11:02:36.775 | ERROR    | boxmot.utils.checks:check_packages:26 - (pandas 1.1.4 (/opt/conda/lib/python3.8/site-packages), Requirement.parse('pandas>=1.2'), {'seaborn'})
2023-10-06 11:02:36.775 | WARNING  | boxmot.utils.checks:check_packages:29 - 
Missing packages: "ultralytics @ git+https://github.com/mikel-brostrom/ultralytics.git" 
Atempting installation...
2023-10-06 11:02:36.856 | ERROR    | boxmot.utils.checks:check_packages:26 - (pandas 1.1.4 (/opt/conda/lib/python3.8/site-packages), Requirement.parse('pandas>=1.2'), {'seaborn'})
2023-10-06 11:02:36.857 | WARNING  | boxmot.utils.checks:check_packages:29 - 
Missing packages: "ultralytics @ git+https://github.com/mikel-brostrom/ultralytics.git" 
Atempting installation...
2023-10-06 11:02:38.355 | SUCCESS  | boxmot.utils.checks:check_packages:35 - All the missing packages were installed successfully
2023-10-06 11:02:38.424 | SUCCESS  | boxmot.utils.checks:check_packages:35 - All the missing packages were installed successfully
WARNING ⚠️ 'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING ⚠️ 'ultralytics.yolo.engine' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.engine' instead.
WARNING ⚠️ 'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING ⚠️ 'ultralytics.yolo.engine' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.engine' instead.
2023-10-06 11:02:44.557 | INFO     | examples.detectors.yolox:__init__:62 - Loading yolox_n with yolox_n.pt
2023-10-06 11:02:44.585 | INFO     | examples.detectors.yolox:__init__:62 - Loading yolox_n with yolox_n.pt


2023-10-06 11:02:50.887 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:207 - Successfully loaded pretrained weights from "osnet_ain_x1_0_msmt17.pt"
2023-10-06 11:02:50.888 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:211 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')
2023-10-06 11:02:50.917 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:207 - Successfully loaded pretrained weights from "osnet_ain_x1_0_msmt17.pt"
2023-10-06 11:02:50.918 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:211 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')
Traceback (most recent call last):
  File "/workspace/yolo_tracking/examples/track.py", line 199, in <module>
    run(opt)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/yolo_tracking/examples/track.py", line 103, in run
    for frame_idx, r in enumerate(results):
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 44, in generator_context
    response = gen.send(None)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 241, in stream_inference
    self.run_callbacks('on_predict_start')
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 358, in run_callbacks
    callback(self)
  File "/workspace/yolo_tracking/examples/track.py", line 54, in on_predict_start
    tracker.model.warmup()
  File "/workspace/yolo_tracking/boxmot/appearance/reid_multibackend.py", line 294, in warmup
    im = self.preprocess(xyxys=np.array([[0, 0, 128, 256]]), img=im)
  File "/workspace/yolo_tracking/boxmot/appearance/reid_multibackend.py", line 215, in preprocess
    crops = torch.permute(crops, (0, 3, 1, 2))
AttributeError: module 'torch' has no attribute 'permute'
Traceback (most recent call last):
  File "/workspace/yolo_tracking/examples/track.py", line 199, in <module>
    run(opt)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/yolo_tracking/examples/track.py", line 103, in run
    for frame_idx, r in enumerate(results):
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 44, in generator_context
    response = gen.send(None)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 241, in stream_inference
    self.run_callbacks('on_predict_start')
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 358, in run_callbacks
    callback(self)
  File "/workspace/yolo_tracking/examples/track.py", line 54, in on_predict_start
    tracker.model.warmup()
  File "/workspace/yolo_tracking/boxmot/appearance/reid_multibackend.py", line 294, in warmup
    im = self.preprocess(xyxys=np.array([[0, 0, 128, 256]]), img=im)
  File "/workspace/yolo_tracking/boxmot/appearance/reid_multibackend.py", line 215, in preprocess
    crops = torch.permute(crops, (0, 3, 1, 2))
AttributeError: module 'torch' has no attribute 'permute'
2023-10-06 11:02:52.614 | SUCCESS  | __main__:eval:220 - Evaluation succeeded
val: yolo_model=yolox_n.pt, reid_model=osnet_ain_x1_0_msmt17.pt, tracking_method=deepocsort, name=exp, classes=['0'], project=/workspace/yolo_tracking/runs/val, exist_ok=False, gsi=False, benchmark=dancetrack, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], save=True, processes_per_device=2
2023-10-06 11:02:52.957 | ERROR    | __main__:eval:255 - Traceback (most recent call last):
  File "/workspace/yolo_tracking/examples/val_utils/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/workspace/yolo_tracking/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: mot//dancetrack0074.txt

2023-10-06 11:02:52.958 | ERROR    | __main__:eval:256 - 
Eval Config:
USE_PARALLEL         : True                          
NUM_PARALLEL_CORES   : 4                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /workspace/yolo_tracking/examples/val_utils/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /workspace/yolo_tracking/examples/val_utils/data/dancetrack/train
TRACKERS_FOLDER      : /workspace/yolo_tracking/runs/val/exp9
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['mot']                       
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            :                               
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   :                               
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : {'dancetrack0074': None, 'dancetrack0032': None, 'dancetrack0049': None, 'dancetrack0023': None, 'dancetrack0075': None, 'dancetrack0037': None, 'dancetrack0061': None, 'dancetrack0006': None, 'dancetrack0057': None, 'dancetrack0080': None, 'dancetrack0082': None, 'dancetrack0099': None, 'dancetrack0052': None, 'dancetrack0055': None, 'dancetrack0072': None, 'dancetrack0024': None, 'dancetrack0016': None, 'dancetrack0044': None, 'dancetrack0008': None, 'dancetrack0066': None, 'dancetrack0086': None, 'dancetrack0002': None, 'dancetrack0051': None, 'dancetrack0069': None, 'dancetrack0012': None, 'dancetrack0096': None, 'dancetrack0015': None, 'dancetrack0053': None, 'dancetrack0045': None, 'dancetrack0033': None, 'dancetrack0098': None, 'dancetrack0027': None, 'dancetrack0020': None, 'dancetrack0068': None, 'dancetrack0087': None, 'dancetrack0083': None, 'dancetrack0039': None, 'dancetrack0001': None, 'dancetrack0029': None, 'dancetrack0062': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : True                          
Tracker file not found: /workspace/yolo_tracking/runs/val/exp9/mot/dancetrack0074.txt

**Comment by mikel-brostrom** [comment]
The first error appears here:

```bash
File "/workspace/yolo_tracking/boxmot/appearance/reid_multibackend.py", line 215, in preprocess
crops = torch.permute(crops, (0, 3, 1, 2))
AttributeError: module 'torch' has no attribute 'permute'
```

**Comment by mikel-brostrom** [comment]
Try to upgrade torch:

`pip install torch --upgrade`

**Comment by chenke225** [comment]
I am sorry for unclear discription.
My command 
```
python examples/val.py --tracking-method strongsort --benchmark MOT17 --save --imgsz 960
```
There is one error:
trackeval.utils.TrackEvalException: Tracker file not found: mot//MOT17-02-FRCNN.txt

My FULL Error log:

val: yolo_model=/home/chenke/yolo_tracking/examples/weights/yolov8s.pt, reid_model=/home/chenke/yolo_tracking/examples/weights/osnet_x0_25_msmt17.pt, tracking_method=strongsort, name=exp, classes=['0'], project=/home/chenke/yolo_tracking/runs/val, exist_ok=False, gsi=False, benchmark=MOT17, split=train, eval_existing=False, conf=0.45, imgsz=[960], device=[''], save=True, processes_per_device=2
2023-10-06 07:41:34.922 | ERROR    | __main__:eval:255 - Traceback (most recent call last):
  File "/home/chenke/yolo_tracking/examples/val_utils/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/home/chenke/yolo_tracking/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: mot//MOT17-02-FRCNN.txt

2023-10-06 07:41:34.923 | ERROR    | __main__:eval:256 - 
Eval Config:
USE_PARALLEL         : True                          
NUM_PARALLEL_CORES   : 4                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /home/chenke/yolo_tracking/examples/val_utils/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /home/chenke/yolo_tracking/examples/val_utils/data/MOT17/train
TRACKERS_FOLDER      : /home/chenke/yolo_tracking/runs/val/exp20
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['mot']                       
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            :                               
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   :                               
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : {'MOT17-02-FRCNN': None, 'MOT17-04-FRCNN': None, 'MOT17-05-FRCNN': None, 'MOT17-09-FRCNN': None, 'MOT17-10-FRCNN': None, 'MOT17-11-FRCNN': None, 'MOT17-13-FRCNN': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : True                          
Tracker file not found: /home/chenke/yolo_tracking/runs/val/exp20/mot/MOT17-02-FRCNN.txt 

I think that the error happens because i use command "--save" which results mot tracker file don't been produced.
So, when i delete the command "--save", such that the command is:
```
python examples/val.py  --tracking-method strongsort --benchmark MOT17 --imgsz 960
```
That is all, every things OK!

**Comment by datct00** [comment]
Thank you for reply

> You can try to upgrade torch:
> 
> `pip install torch --upgrade`

Thank you for replying. The error is solved!

**Comment by mikel-brostrom** [comment]
Great!

Did this:

> > You can try to upgrade torch:
> > `pip install torch --upgrade`

 solve it?

**Comment by datct00** [comment]
Yes, there is a confliction of your torch version with my torch version so the error was solved by this `pip install torch --upgrade`
