### ISSUE TITLE
Hybridsort without Reid Model

### ISSUE THREAD

**Issue by Harini-tech** [mikel-brostrom/yolo_tracking#1145]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I'm trying to run **HybridSort without the Reid model**. Could you please guide me on how to resolve this issue?

python3.8  examples/track.py --yolo-model yolov8m.pt  --source Input.mp4 --save  --tracking-method hybridsort_wo_reid
WARNING ⚠️ 'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING ⚠️ 'ultralytics.yolo.engine' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.engine' instead.

2023-10-11 12:56:02.196965 video 1/1 (1/62266) Input.mp4: 384x640 2 cars, 340.3ms
Traceback (most recent call last):
  File "examples/track.py", line 199, in <module>
    run(opt)
  File "henv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "examples/track.py", line 103, in run
    for frame_idx, r in enumerate(results):
  File "henv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "henv/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 262, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  File "henv/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 358, in run_callbacks
    callback(self)
  File "henv/lib/python3.8/site-packages/ultralytics/trackers/track.py", line 49, in on_predict_postprocess_end
    tracks = predictor.trackers[i].update(det, im0s[i])
  File "HybridSORT_mikel/yolo_tracking/boxmot/utils/__init__.py", line 53, in wrapper
    dets = self.update(instance, modified_args[0], im)
  File "HybridSORT_mikel/yolo_tracking/boxmot/trackers/hybridsort/hybridsort_without_reid.py", line 436, in update
    matched, unmatched_dets, unmatched_trks = associate_4_points_with_score(
  File "HybridSORT_mikel/yolo_tracking/boxmot/trackers/hybridsort/association.py", line 453, in associate_4_points_with_score
    iou_matrix = iou_type(detections, trackers)
TypeError: 'int' object is not callable

**Comment by mikel-brostrom** [comment]
I suggest you have a look at the original implementation for this :smile:
