### ISSUE TITLE
The example code does not work

### ISSUE THREAD

**Issue by fukuda-A-HU** [mikel-brostrom/yolo_tracking#1159]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

PS --- --- \yolo_tracking> python examples/track.py --source 0

1/1: 0... Success  (inf frames of shape 640x480 at 30.00 FPS)

2023-10-24 16:39:27.935 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:207 - Successfully loaded pretrained weights from "C:\Users\hakat\Documents\intern_nouh\yolo_tracking\examples\weights\osnet_x0_25_msmt17.pt"
2023-10-24 16:39:27.936 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:211 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')
Traceback (most recent call last):
  File "--- --- \yolo_tracking\examples\track.py", line 199, in <module>
    run(opt)
  File "--- --- \env\nauh_env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "--- --- \yolo_tracking\examples\track.py", line 103, in run
    for frame_idx, r in enumerate(results):
  File "--- --- \env\nauh_env\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "--- --- \env\nauh_env\lib\site-packages\ultralytics\engine\predictor.py", line 264, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  File "--- --- \env\nauh_env\lib\site-packages\ultralytics\engine\predictor.py", line 358, in run_callbacks
    callback(self)
  File "--- --- \env\nauh_env\lib\site-packages\ultralytics\trackers\track.py", line 48, in on_predict_postprocess_end
    tracks = predictor.trackers[i].update(det, im0s[i])
  File "--- --- \yolo_tracking\boxmot\trackers\deepocsort\deep_ocsort.py", line 369, in update
    assert isinstance(dets, np.ndarray), f"Unsupported 'dets' input type '{type(dets)}', valid format is np.ndarray"
AssertionError: Unsupported 'dets' input type '<class 'ultralytics.engine.results.Boxes'>', valid format is np.ndarray

### Environment

Python 3.10.5 

### Minimal Reproducible Example

Python examples/track.py --source 0

**Comment by fukuda-A-HU** [comment]
An easy solution is to add the following line to deep_ocsort.py around line 366

    def update(self, dets, img):
        """
        Params:
          dets - a numpy array of detections in the format [[x1,y1,x2,y2,score],[x1,y1,x2,y2,score],...]
        Requires: this method must be called once for each frame even with empty detections
        (use np.empty((0, 5)) for frames without detections).
        Returns the a similar array, where the last column is the object ID.
        NOTE: The number of objects returned may differ from the number of detections provided.
        """

        dets = dets.data # I added this line

        assert isinstance(dets, np.ndarray), f"Unsupported 'dets' input type '{type(dets)}', valid format is np.ndarray"
        assert isinstance(img, np.ndarray), f"Unsupported 'img' input type '{type(img)}', valid format is np.ndarray"
        assert len(dets.shape) == 2, "Unsupported 'dets' dimensions, valid number of dimensions is two"
        assert dets.shape[1] == 6, "Unsupported 'dets' 2nd dimension lenght, valid lenghts is 6"

**Comment by mikel-brostrom** [comment]
If you don't follow the repo's installation guide you will ecounter problems
