### ISSUE TITLE
HybridSORT fails due to Numpy Version

### ISSUE THREAD

**Issue by florian-fischer-swarm** [mikel-brostrom/yolo_tracking#1221]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

Running HybridSort fails with the following error:

```
File "/home/fisf/anaconda3/envs/swarmdnninference/lib/python3.11/site-packages/boxmot/trackers/hybridsort/hybridsort.py", line 442, in update
    dtype=np.float)
          ^^^^^^^^
  File "/home/fisf/anaconda3/envs/swarmdnninference/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
```

Those aliases have been deprecated in numpy 1.20, and the deprecations expired in 1.24.0 (see https://numpy.org/devdocs/release/1.24.0-notes.html).

I propose simply changing the dtypes to float64. If you agree I can send a PR.

### Environment

v10.0.46

### Minimal Reproducible Example

n/a

**Comment by mikel-brostrom** [comment]
Shouldn't be an issue with the numpy version in the requirements (1.24.4)?

**Comment by anirudth** [comment]
I faced a similar issue. I updated the following in the source code and the inconsistency was patched. Changes needed were:
1. changing dtype behavior from np.float to np.float64
2. changing how we retireve the kalman filter scores
3. updating the tracker update call. 

@florian-fischer-swarm  apply the following patch on the source code to solve the issues. 
@mikel-brostrom  I can create a pull request for these changes if you're fine. 
```
diff --git a/boxmot/trackers/hybridsort/association.py b/boxmot/trackers/hybridsort/association.py
index bfe9e92..80b1612 100644
--- a/boxmot/trackers/hybridsort/association.py
+++ b/boxmot/trackers/hybridsort/association.py
@@ -672,13 +672,13 @@ def embedding_distance(tracks_feat, detections_feat, metric='cosine'):
     :return: cost_matrix np.ndarray
     """
 
-    cost_matrix = np.zeros((len(tracks_feat), len(detections_feat)), dtype=np.float)
+    cost_matrix = np.zeros((len(tracks_feat), len(detections_feat)), dtype=np.float64)
     if cost_matrix.size == 0:
         return cost_matrix
-    # det_features = np.asarray([track.curr_feat for track in detections], dtype=np.float)    # [detection_num, emd_dim]
+    # det_features = np.asarray([track.curr_feat for track in detections], dtype=np.float64)    # [detection_num, emd_dim]
     # #for i, track in enumerate(tracks):
     #     #cost_matrix[i, :] = np.maximum(0.0, cdist(track.smooth_feat.reshape(1,-1), det_features, metric))
-    # track_features = np.asarray([track.smooth_feat for track in tracks], dtype=np.float)    # [track_num, emd_dim]
+    # track_features = np.asarray([track.smooth_feat for track in tracks], dtype=np.float64)    # [track_num, emd_dim]
     # Nomalized features, metric: cosine, [track_num, detection_num]
     cost_matrix = np.maximum(0.0, cdist(tracks_feat, detections_feat, metric))
     return cost_matrix
diff --git a/boxmot/trackers/hybridsort/hybridsort.py b/boxmot/trackers/hybridsort/hybridsort.py
index 216d0c1..e113da9 100644
--- a/boxmot/trackers/hybridsort/hybridsort.py
+++ b/boxmot/trackers/hybridsort/hybridsort.py
@@ -415,7 +415,7 @@ class HybridSORT(object):
             try:
                 trk[:6] = [pos[0][0], pos[0][1], pos[0][2], pos[0][3], kalman_score, simple_score[0]]
             except Exception:
-                trk[:6] = [pos[0][0], pos[0][1], pos[0][2], pos[0][3], kalman_score, simple_score]
+                trk[:6] = [pos[0][0], pos[0][1], pos[0][2], pos[0][3], kalman_score[0], simple_score]
             if np.any(np.isnan(pos)):
                 to_del.append(t)
         trks = np.ma.compress_rows(np.ma.masked_invalid(trks))
@@ -439,11 +439,11 @@ class HybridSORT(object):
         """
         if self.EG_weight_high_score > 0 and self.TCM_first_step:
             track_features = np.asarray([track.smooth_feat for track in self.trackers],
-                                        dtype=np.float)
+                                        dtype=np.float64)
             emb_dists = embedding_distance(track_features, id_feature_keep).T
             if self.with_longterm_reid or self.with_longterm_reid_correction:
                 long_track_features = np.asarray([np.vstack(list(track.features)).mean(0) for track in self.trackers],
-                                                 dtype=np.float)
+                                                 dtype=np.float64)
                 assert track_features.shape == long_track_features.shape
                 long_emb_dists = embedding_distance(long_track_features, id_feature_keep).T
                 assert emb_dists.shape == long_emb_dists.shape
@@ -491,7 +491,7 @@ class HybridSORT(object):
                     )
                     iou_left_thre = iou_left
                 if self.EG_weight_low_score > 0:
-                    u_track_features = np.asarray([track.smooth_feat for track in u_tracklets], dtype=np.float)
+                    u_track_features = np.asarray([track.smooth_feat for track in u_tracklets], dtype=np.float64)
                     emb_dists_low_score = embedding_distance(u_track_features, id_feature_second).T
                     matched_indices = linear_assignment(-iou_left + self.EG_weight_low_score * emb_dists_low_score,
                                                         )
@@ -510,6 +510,7 @@ class HybridSORT(object):
                             continue
                     self.trackers[trk_ind].update(
                         dets_second[det_ind, :],
+                        dets0[det_ind, 5], dets0[det_ind, 6],
                         id_feature_second[det_ind, :],
                         update_feature=False
                     )     # [hgx0523] do not update with id feature
```

**Comment by mikel-brostrom** [comment]
If the deprecation expired in `1.24.0` and the `np` version in the requirements is `1.24.4`. It is all good? CI is passing with the current `np` version...

**Comment by florian-fischer-swarm** [comment]
Hi,
the patch by @anirudth is roughly what I applied to get it working.
The thing is, it expired in 1.24.0, so technically only a version *below* that should run cleanly with the HybridSort implementation.

I verified that locally as follows:
```
(yolo_tracking) fisf@gpu02:~/code/yolo_tracking$ pip list
Package                  Version      Editable project location
------------------------ ------------ -----------------------------
absl-py                  2.0.0
beautifulsoup4           4.12.2
boxmot                   10.0.46      /home/fisf/code/yolo_tracking
cachetools               5.3.2
certifi                  2023.11.17
cfgv                     3.4.0
charset-normalizer       3.3.2
contourpy                1.2.0
cycler                   0.12.1
Cython                   3.0.6
distlib                  0.3.8
filelock                 3.13.1
filterpy                 1.4.5
fonttools                4.46.0
fsspec                   2023.12.2
ftfy                     6.1.3
gdown                    4.7.1
gitdb                    4.0.11
GitPython                3.1.40
google-auth              2.25.2
google-auth-oauthlib     1.1.0
grpcio                   1.60.0
identify                 2.5.33
idna                     3.6
Jinja2                   3.1.2
joblib                   1.3.2
kiwisolver               1.4.5
lapx                     0.5.5
loguru                   0.7.2
Markdown                 3.5.1
MarkupSafe               2.1.3
matplotlib               3.8.2
mpmath                   1.3.0
networkx                 3.2.1
nodeenv                  1.8.0
numpy                    1.24.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
oauthlib                 3.2.2
opencv-python            4.8.1.78
packaging                23.2
pandas                   2.1.4
Pillow                   10.1.0
pip                      23.2.1
platformdirs             4.1.0
pre-commit               3.6.0
protobuf                 4.23.4
psutil                   5.9.6
py-cpuinfo               9.0.0
pyasn1                   0.5.1
pyasn1-modules           0.3.0
pyparsing                3.1.1
PySocks                  1.7.1
python-dateutil          2.8.2
pytz                     2023.3.post1
PyYAML                   6.0.1
regex                    2023.10.3
requests                 2.31.0
requests-oauthlib        1.3.1
rsa                      4.9
scikit-learn             1.3.2
scipy                    1.11.4
seaborn                  0.13.0
setuptools               68.2.0
six                      1.16.0
smmap                    5.0.1
soupsieve                2.5
sympy                    1.12
tensorboard              2.15.1
tensorboard-data-server  0.7.2
threadpoolctl            3.2.0
torch                    2.1.1
torchvision              0.16.1
tqdm                     4.66.1
triton                   2.1.0
typing_extensions        4.9.0
tzdata                   2023.3
ultralytics              8.0.146
urllib3                  2.1.0
virtualenv               20.25.0
wcwidth                  0.2.12
Werkzeug                 3.0.1
wheel                    0.41.2
yacs                     0.1.8
```

Executing the CI test case for HybridSort yields this error for me.

```
(yolo_tracking) fisf@gpu02:~/code/yolo_tracking$  python examples/track.py --tracking-method hybridsort --source $IMG --imgsz 320
WARNING ⚠️ 'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING ⚠️ 'ultralytics.yolo.engine' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.engine' instead.

2023-12-18 08:59:28.775 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:207 - Successfully loaded pretrained weights from "/home/fisf/code/yolo_tracking/examples/weights/osnet_x0_25_msmt17.pt"
2023-12-18 08:59:28.775 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:211 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')
Traceback (most recent call last):
  File "/home/fisf/code/yolo_tracking/examples/track.py", line 199, in <module>
    run(opt)
  File "/home/fisf/.virtualenvs/yolo_tracking/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/fisf/code/yolo_tracking/examples/track.py", line 103, in run
    for frame_idx, r in enumerate(results):
  File "/home/fisf/.virtualenvs/yolo_tracking/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/fisf/.virtualenvs/yolo_tracking/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 262, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  File "/home/fisf/.virtualenvs/yolo_tracking/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 358, in run_callbacks
    callback(self)
  File "/home/fisf/.virtualenvs/yolo_tracking/lib/python3.10/site-packages/ultralytics/trackers/track.py", line 49, in on_predict_postprocess_end
    tracks = predictor.trackers[i].update(det, im0s[i])
  File "/home/fisf/code/yolo_tracking/boxmot/utils/__init__.py", line 53, in wrapper
    dets = self.update(instance, modified_args[0], im)
  File "/home/fisf/code/yolo_tracking/boxmot/trackers/hybridsort/hybridsort.py", line 442, in update
    dtype=np.float)
  File "/home/fisf/.virtualenvs/yolo_tracking/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

```
(yolo_tracking) fisf@gpu02:~/code/yolo_tracking$ echo $?
1
```

Now, my first suspicion was that the CI action does not run in fail-fast mode. But apparently Github uses` set -e` as default for bash and sh. :shrug:

**Comment by mikel-brostrom** [comment]
I see. @florian-fischer-swarm are you still up for sending a PR?

**Comment by florian-fischer-swarm** [comment]
Sure, give me a day to clean up stuff. Tho I have to admit, that I have no clue why the CI run passes.

**Comment by mikel-brostrom** [comment]
> Sure, give me a day to clean up stuff. Tho I have to admit, that I have no clue why the CI run passes.

I can have a look at the changes :smile:

**Comment by florian-fischer-swarm** [comment]
Opened a PR, this also includes a fix for another error (see the note in the PR).

**Comment by florian-fischer-swarm** [comment]
Thanks!
