### ISSUE TITLE
"--source streams.txt" cannot work

### ISSUE THREAD

**Issue by KKHYA** [mikel-brostrom/yolo_tracking#1224]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi, I want to use ***streams.txt*** as the input source when running the command:

```
python examples/track.py --source streams.txt --show
```

There's an error:

```
Traceback (most recent call last):
  File "track.py", line 199, in <module>
    run(opt)
  File "/home/mingyuan/anaconda3/envs/boxmot/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 103, in run
    for frame_idx, r in enumerate(results):
  File "/home/mingyuan/anaconda3/envs/boxmot/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/mingyuan/anaconda3/envs/boxmot/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 229, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "/home/mingyuan/anaconda3/envs/boxmot/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 210, in setup_source
    self.dataset = load_inference_source(source=source, imgsz=self.imgsz, vid_stride=self.args.vid_stride)
  File "/home/mingyuan/anaconda3/envs/boxmot/lib/python3.8/site-packages/ultralytics/data/build.py", line 165, in load_inference_source
    dataset = LoadImages(source, imgsz=imgsz, vid_stride=vid_stride)
  File "/home/mingyuan/anaconda3/envs/boxmot/lib/python3.8/site-packages/ultralytics/data/loaders.py", line 183, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: 0 does not exist
```

But when I use "--source 0", it can work which makes me really confused.
The content in my txt file is:

```
0
```

Do you know how to fix it? Thanks!

**Comment by mikel-brostrom** [comment]
This is a question for the official Ultralytics repo which I am using as dataloader :smile:
