### ISSUE TITLE
About using CLIP-ReID model

### ISSUE THREAD

**Issue by thptai** [mikel-brostrom/yolo_tracking#1282]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi, thanks for your great repos.

I have tried to use CLIP-ReID as reid model in your framework.
Everything is fine if I use the default  
` model_weights = Path('clip_market1501.pt') '

However, I have tried to train on the original repo (https://github.com/Syliz517/CLIP-ReID/tree/master)
I used my trained weights and this happened

Traceback (most recent call last):
  File "pita_test.py", line 197, in <module>
    run(opt)
  File "pita_test.py", line 84, in run
    tracker = BoTSORT(
  File "/home/vsw4/pita/ECC4_2024/AICity2024/yolo_tracking/boxmot/trackers/botsort/bot_sort.py", line 224, in __init__
    self.model = ReIDDetectMultiBackend(
  File "/home/vsw4/pita/ECC4_2024/AICity2024/yolo_tracking/boxmot/appearance/reid_multibackend.py", line 85, in __init__
    load_pretrained_weights(self.model, w)
  File "/home/vsw4/pita/ECC4_2024/AICity2024/yolo_tracking/boxmot/appearance/reid_model_factory.py", line 178, in load_pretrained_weights
    model.load_param(str(weight_path))
  File "/home/vsw4/pita/ECC4_2024/AICity2024/yolo_tracking/boxmot/appearance/backbones/clip/make_model.py", line 129, in load_param
    self.state_dict()[i.replace('module.', '')].copy_(param_dict[i])
RuntimeError: output with shape [1, 768] doesn't match the broadcast shape [751, 768]

I would like to train the CLIP-ReID model and use my trained weight in your framework.
Thank you.

**Comment by mikel-brostrom** [comment]
I cannot help you out here. I only worked with the pretrained weights on the ReID CLIP repo.

**Comment by thptai** [comment]
> I cannot help you out here. I only worked with the pretrained weights on the ReID CLIP repo.

Did you use the pretrained model they put there ?
I trained on the exact Market1501 dataset too, but the output weight is not fitted to your framework.
I have tried to download the pretrained weight directly from their github and the extension is '.pth', which is different from '.pt'.

**Comment by mikel-brostrom** [comment]
`Did you use the pretrained model they put there ?`

Yes

>  I have tried to download the pretrained weight directly from their github and the extension is '.pth', which is different from '.pt'.

Both `.pt` and `.pth` file extensions are used interchangeably in PyTorch for saving and loading the state of a model. The choice between .pt and .pth is more a matter of personal or community preference rather than a technical difference in how the data is stored or processed. Both file types are used to serialize PyTorch objects using Python's pickle module, and can be loaded using PyTorch's torch.load() function.

**Comment by choidaedae** [comment]
Hello, I have a same issue. How did you solve this problem?
