### ISSUE TITLE
'types.SimpleNamespace' object has no attribute 'det_thresh'

### ISSUE THREAD

**Issue by rslim97** [mikel-brostrom/yolo_tracking#1294]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evolution

### Bug

I am trying to tune parameters for hybridsort when I get this error:

```
evolve: yolo_model=/home/rslim/proj/rslim/yolo_tracking/examples/weights/yolov8n.pt, reid_model=/home/rslim/proj/rslim/yolo_tracking/examples/weights/osnet_x0_25_msmt17.pt, tracking_method=hybridsort, name=exp, project=/home/rslim/proj/rslim/yolo_tracking/examples/runs/evolve, classes=['0'], exist_ok=False, benchmark=MOT16, split=train, eval_existing=, conf=0.45, imgsz=[1280], gsi=False, device=[''], n_trials=100, resume=False, save=False, processes_per_device=2, objectives=['HOTA', 'MOTA', 'IDF1'], tracking_config=/home/rslim/proj/rslim/yolo_tracking/boxmot/configs/hybridsort.yaml
[I 2024-02-13 12:11:52,407] A new study created in memory with name: no-name-ce2c2921-775d-45c4-baee-39408100a50e
2024-02-13 12:11:52.409 | INFO     | __main__:get_new_config:178 - Writing newly generated config for trial
Namespace(benchmark='MOT16', classes=['0'], conf=0.3993758979779549, device=[''], eval_existing='', exist_ok=False, gsi=False, imgsz=[1280], n_trials=100, name='exp', objectives=['HOTA', 'MOTA', 'IDF1'], processes_per_device=2, project=PosixPath('/home/rslim/proj/rslim/yolo_tracking/examples/runs/evolve'), reid_model=PosixPath('/home/rslim/proj/rslim/yolo_tracking/examples/weights/osnet_x0_25_msmt17.pt'), resume=False, save=False, split='train', tracking_config=PosixPath('/home/rslim/proj/rslim/yolo_tracking/boxmot/configs/hybridsort.yaml'), tracking_method='hybridsort', yolo_model=PosixPath('/home/rslim/proj/rslim/yolo_tracking/examples/weights/yolov8n.pt'))
2024-02-13 12:11:52.452 | INFO     | val:download_mot_eval_tools:65 - Eval repo already downloaded Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/JonathonLuiten/TrackEval /home/rslim/proj/rslim/yolo_tracking/examples/val_utils
  stderr: 'fatal: destination path '/home/rslim/proj/rslim/yolo_tracking/examples/val_utils' already exists and is not an empty directory.
'
sed: no input files
sed: no input files
sed: no input files
2024-02-13 12:12:00.627 | INFO     | val:eval:203 - Staring evaluation process on /home/rslim/proj/rslim/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-02/img1
2024-02-13 12:12:00.649 | INFO     | val:eval:203 - Staring evaluation process on /home/rslim/proj/rslim/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-04/img1


Traceback (most recent call last):
  File "/home/rslim/proj/rslim/yolo_tracking/examples/track.py", line 197, in <module>
    run(opt)
  File "/home/rslim/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/rslim/proj/rslim/yolo_tracking/examples/track.py", line 103, in run
    for frame_idx, r in enumerate(results):
  File "/home/rslim/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/rslim/miniconda3/envs/boxmot_env/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 252, in stream_inference
    self.run_callbacks('on_predict_start')
  File "/home/rslim/miniconda3/envs/boxmot_env/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 377, in run_callbacks
    callback(self)
  File "/home/rslim/proj/rslim/yolo_tracking/examples/track.py", line 44, in on_predict_start
    tracker = create_tracker(
  File "/home/rslim/proj/rslim/yolo_tracking/boxmot/tracker_zoo.py", line 107, in create_tracker
    det_thresh=cfg.det_thresh,
AttributeError: 'types.SimpleNamespace' object has no attribute 'det_thresh'
```

I have modified the config file to include said parameter but of no effect. When I rerun the command, it rewrites the hybridsort.yaml file into this and empty dict, like this:
```
{}
```

### Environment

-python 3.8.10 -ultralytics 8.0.228 -torch 2.1.2

### Minimal Reproducible Example

cd yolo_tracking
python3 evolve.py --tracking-method hybridsort --benchmark MOT16 --n-trials 100

**Comment by mikel-brostrom** [comment]
1. You need to add the config file here: https://github.com/mikel-brostrom/yolo_tracking/tree/master/boxmot/configs
2. Add a block of parameter suggestions like this one: https://github.com/mikel-brostrom/yolo_tracking/blob/09c4f226008c2b0f0806cdfc0cbddaa979c7ba43/examples/evolve.py#L121C9-L141

**Comment by mikel-brostrom** [comment]
I would be more than happy to review a PR for this! :smile:

**Comment by mikel-brostrom** [comment]
Merged! Thx for contributing to this repo @rslim97 :rocket:

**Comment by JAYUAN12** [comment]
@mikel-brostrom  Dear author, I also added config according to your method, but the following error message still appears：
Traceback (most recent call last):
  File "E:\boxmot-v.10.1\boxmot-v.10.1\examples\track.py", line 230, in <module>
    main(opt)
  File "E:\boxmot-v.10.1\boxmot-v.10.1\examples\track.py", line 225, in main
    run(vars(opt))
  File "D:\Annocanda\envs\yolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\boxmot-v.10.1\boxmot-v.10.1\examples\track.py", line 97, in run
    predictor.run_callbacks('on_predict_start')
  File "D:\Annocanda\envs\yolo\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 339, in run_callbacks
    callback(self)
  File "E:\boxmot-v.10.1\boxmot-v.10.1\examples\track.py", line 35, in on_predict_start
    tracker = create_tracker(
  File "D:\Annocanda\envs\yolo\lib\site-packages\boxmot\tracker_zoo.py", line 93, in create_tracker
    det_thresh=cfg.det_thresh,
AttributeError: 'types.SimpleNamespace' object has no attribute 'det_thresh'
![image](https://github.com/user-attachments/assets/063b5c7a-1e36-49a6-8c22-88ceae389a44)

**Comment by mikel-brostrom** [comment]
I really recommend you to upgrade the version you are using. I am not providing support for 10.1 if that is really the version you are using

**Comment by JAYUAN12** [comment]
> I really recommend you to upgrade the version you are using. I am not providing support for 10.1 if that is really the version you are using

But isn't version 10.1 the latest?

**Comment by mikel-brostrom** [comment]
10.0.73 is the latest

**Comment by JAYUAN12** [comment]
> 10.0.73 is the latest

thanks my fault!

**Comment by JAYUAN12** [comment]
Dear author, hello, now I encountered a new problem, I looked for some information, but I could not solve it, I ran val.py version 0.73 error content is as follows:
D:\Annocanda\envs\yolo\python.exe E:\boxmot-10.0.73\boxmot-10.0.73\tracking\val.py 
2024-07-12 21:08:45.879 | INFO     | tracking.utils:download_mot_eval_tools:38 - Evaluation repo already downloaded or an error occurred: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/JonathonLuiten/TrackEval E:\boxmot-10.0.73\boxmot-10.0.73\tracking\val_utils
  stderr: 'fatal: destination path 'E:\boxmot-10.0.73\boxmot-10.0.73\tracking\val_utils' already exists and is not an empty directory.
'
Traceback (most recent call last):
  File "E:\boxmot-10.0.73\boxmot-10.0.73\tracking\val.py", line 177, in <module>
    run_trackeval(None)
  File "E:\boxmot-10.0.73\boxmot-10.0.73\tracking\val.py", line 167, in run_trackeval
    download_mot_eval_tools(val_tools_path)
  File "E:\boxmot-10.0.73\boxmot-10.0.73\tracking\utils.py", line 45, in download_mot_eval_tools
    grep_result = subprocess.run(grep_cmd, stdout=subprocess.PIPE, text=True)
  File "D:\Annocanda\envs\yolo\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Annocanda\envs\yolo\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Annocanda\envs\yolo\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Process finished with exit code 1
