### ISSUE TITLE
AttributeError: 'DeepOCSort' object has no attribute 'reset'

### ISSUE THREAD

**Issue by Howardlei123** [mikel-brostrom/yolo_tracking#1295]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\yolo_tracking\examples\track.py", line 200, in <module>
    run(opt)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\Admin\Desktop\yolo_tracking\examples\track.py", line 104, in run
    for frame_idx, r in enumerate(results):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\predictor.py", line 292, in stream_inference
    self.run_callbacks("on_predict_postprocess_end")
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\predictor.py", line 401, in run_callbacks
    callback(self)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\trackers\track.py", line 58, in on_predict_postprocess_end
    predictor.trackers[i].reset()
AttributeError: 'DeepOCSort' object has no attribute 'reset'

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/issues/1263#issuecomment-1898657606
