### ISSUE TITLE
Error when running tracking part CUDA_VISIBLE_DEVICES="1" python examples/track.py --yolo-model yolov8s --source /data/video_batch_fps_10_1.mp4

### ISSUE THREAD

**Issue by mominali12** [mikel-brostrom/yolo_tracking#1303]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

**What is the possible reason for the following error?** 

### Following is the error I am getting

`It seems like some environment issue. I am using a virtual environment created using pyenv`

Traceback (most recent call last):
  File "/home/mal/BoxMOT/yolo_tracking/examples/track.py", line 200, in <module>
    run(opt)
  File "/data22/mal/.pyenv/versions/3.10.6/envs/env_boxMOT/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/mal/BoxMOT/yolo_tracking/examples/track.py", line 104, in run
    for frame_idx, r in enumerate(results):
  File "/data22/mal/.pyenv/versions/3.10.6/envs/env_boxMOT/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/data22/mal/.pyenv/versions/3.10.6/envs/env_boxMOT/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 252, in stream_inference
    self.run_callbacks('on_predict_start')
  File "/data22/mal/.pyenv/versions/3.10.6/envs/env_boxMOT/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 377, in run_callbacks
    callback(self)
  File "/home/mal/BoxMOT/yolo_tracking/examples/track.py", line 44, in on_predict_start
    tracker = create_tracker(
  File "/data22/mal/.pyenv/versions/3.10.6/envs/env_boxMOT/lib/python3.10/site-packages/boxmot/tracker_zoo.py", line 86, in create_tracker
    deepocsort = DeepOCSort(
  File "/data22/mal/.pyenv/versions/3.10.6/envs/env_boxMOT/lib/python3.10/site-packages/boxmot/trackers/deepocsort/deep_ocsort.py", line 349, in __init__
    self.model = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
  File "/data22/mal/.pyenv/versions/3.10.6/envs/env_boxMOT/lib/python3.10/site-packages/boxmot/appearance/reid_multibackend.py", line 64, in __init__
    gdown.download(model_url, str(w), quiet=False)
  File "/data22/mal/.pyenv/versions/3.10.6/envs/env_boxMOT/lib/python3.10/site-packages/gdown/download.py", line 215, in download
    for file in os.listdir(osp.dirname(output) or "."):
FileNotFoundError: [Errno 2] No such file or directory: '/data22/mal/.pyenv/versions/3.10.6/envs/env_boxMOT/lib/python3.10/site-packages/examples/weights'

**Comment by mikel-brostrom** [comment]
Maybe create a folder `weights` under `examples`?
