### ISSUE TITLE
RuntimeError while using segmentation + non deepocsort tracking method

### ISSUE THREAD

**Issue by ajdroid** [mikel-brostrom/yolo_tracking#877]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

Hi, I'm having an issue when trying tracking methods other than `deepocsort` and any segmentation model. So far, I've tried to run `botsort`, `strongsort`, and `ocsort` which give errors.  
The error I get is: 
> Traceback (most recent call last):
  File "track.py", line 272, in <module>
    main(opt)
  File "track.py", line 267, in main
    run(**vars(opt))
  File "/home/abhijatbiswas/miniconda3/envs/dataprep/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 194, in run
    s += predictor.write_results(i, predictor.results, (p, im, im0))
  File "/home/abhijatbiswas/miniconda3/envs/dataprep/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 165, in write_results
    self.plotted_img = result.plot(**plot_args)
  File "/home/abhijatbiswas/miniconda3/envs/dataprep/lib/python3.8/site-packages/ultralytics/yolo/engine/results.py", line 222, in plot
    annotator.masks(pred_masks.data, colors=[colors(x, True) for x in idx], im_gpu=img_gpu)
  File "/home/abhijatbiswas/miniconda3/envs/dataprep/lib/python3.8/site-packages/ultralytics/yolo/utils/plotting.py", line 130, in masks
    masks_color = masks * (colors * alpha)  # shape(n,h,w,3)
RuntimeError: The size of tensor a (15) must match the size of tensor b (13) at non-singleton dimension 0

I have tried searching in the ultralytics issues and this repo's issues but not found any mention of this error. 

I was running using the video provided at: `https://github.com/mikel-brostrom/yolov8_tracking/releases/download/v.2.0/test.avi` 

### Minimal Reproducible Example

`python track.py --source test.avi --save --yolo-model yolov8n-seg.pt --tracking-method strongsort`

**Comment by mikel-brostrom** [comment]
Weird, it works on webcam as source but not on a folder containing images...

**Comment by ajdroid** [comment]
I had tried it on videos and folders with images but not webcam. It seems to fail for the former two sources

**Comment by mikel-brostrom** [comment]
Ok, PIP got released. This was next on my TODO list. I tried in thoroughly. Bot pose and segmentation tracking should work with all the trackers. Let's me know if it works for you! :smile:

**Comment by ajdroid** [comment]
Hi, thanks! Even on the latest release, I am seeing issues with `strongsort`:
> Traceback (most recent call last):
  File "examples/track.py", line 246, in <module>
    main(opt)
  File "examples/track.py", line 241, in main
    run(vars(opt))
  File "/home/abhijatbiswas/miniconda3/envs/dataprep/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "examples/track.py", line 165, in run
    s += predictor.write_results(i, predictor.results, (p, im, im0))
  File "/home/abhijatbiswas/miniconda3/envs/dataprep/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 165, in write_results
    self.plotted_img = result.plot(**plot_args)
  File "/home/abhijatbiswas/miniconda3/envs/dataprep/lib/python3.8/site-packages/ultralytics/yolo/engine/results.py", line 222, in plot
    annotator.masks(pred_masks.data, colors=[colors(x, True) for x in idx], im_gpu=img_gpu)
  File "/home/abhijatbiswas/miniconda3/envs/dataprep/lib/python3.8/site-packages/ultralytics/yolo/utils/plotting.py", line 130, in masks
    masks_color = masks * (colors * alpha)  # shape(n,h,w,3)
RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

**Comment by mikel-brostrom** [comment]
`pip install --upgrade boxmot`

**Comment by ajdroid** [comment]
I'm on commit `fd251cd32b4c0f4343c26c4ae7320b9b1e8f35bb` on master

**Comment by mikel-brostrom** [comment]
Seems like only StrongSORT is producing this error... Have tried deepocsort, bytetrack, ocsort and deepocsort

**Comment by mikel-brostrom** [comment]
You can hotfix it by setting:

https://github.com/mikel-brostrom/yolo_tracking/blob/352241150e9592e494547ee5984111c16927faa0/boxmot/strongsort/configs/strongsort.yaml#L4

to 0

**Comment by ajdroid** [comment]
I see -- thanks for this!
One unrelated question I couldn't find the answer to: do you know where the format of the text files produced by enabling `--save_txt` are set? I', not sure how to read the file.
