### ISSUE TITLE
An error with using track.py to test a video file

### ISSUE THREAD

**Issue by Major-Leung** [mikel-brostrom/yolo_tracking#900]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hello. When I input "Python track. py -- source./video/car. mp4" in the terminal, the program displays a RuntimeError: GET was unable to find an engine to execute this calculation.

The details are as follows:

track: yolo_model=/workspace/yolov8_tracking/examples/weights/yolov8n.pt, reid_model=/workspace/yolov8_tracking/examples/weights/mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=deepocsort, source=./video/car.mp4, imgsz=[640], conf=0.5, device=, show=True, save=True, classes=None, project=/workspace/yolov8_tracking/runs/track, name=exp, exist_ok=False, half=False, vid_stride=1, hide_label=False, hide_conf=False, save_txt=False
Traceback (most recent call last):
  File "track.py", line 229, in <module>
    main(opt)
  File "track.py", line 224, in main
    run(vars(opt))
  File "/workspace/track/tracking/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 91, in run
    predictor.model.warmup(imgsz=(1 if predictor.model.pt or predictor.model.triton else predictor.dataset.bs, 3, *predictor.imgsz))
  File "/workspace/track/tracking/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 428, in warmup
    self.forward(im)  # warmup
  File "/workspace/track/tracking/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 314, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/workspace/track/tracking/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/track/tracking/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/workspace/track/tracking/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 60, in _forward_once
    x = m(x)  # run
  File "/workspace/track/tracking/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/track/tracking/lib/python3.8/site-packages/ultralytics/nn/modules/conv.py", line 43, in forward_fuse
    return self.act(self.conv(x))
  File "/workspace/track/tracking/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/track/tracking/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/workspace/track/tracking/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

**Comment by mikel-brostrom** [comment]
Cannot reproduce. A quick search gave me this: https://stackoverflow.com/questions/75776895/runtimeerror-get-was-unable-to-find-an-engine-to-execute-this-computation-when. Seems that you have a CUDA mismatch
