### ISSUE TITLE
Tracking Algorithms cause "RuntimeError: Can't call numpy() on Tensor that requires grad." when running custom model

### ISSUE THREAD

**Issue by sqwatato** [mikel-brostrom/yolo_tracking#908]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

I'm quite new with this kinda of stuff so it my be an issue on my end. 

Every sort I tried using a custom model caused this error:
```
(venv) ➜  YOLO-Test python test.py
/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/examples/weights
/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/examples
Successfully loaded pretrained weights from "mobilenetv2_x1_4_dukemtmcreid.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

0: 416x256 26 heads, 57 persons, 32.3ms
Speed: 2.5ms preprocess, 32.3ms inference, 5.6ms postprocess per image at shape (1, 3, 416, 416)
Traceback (most recent call last):
  File "/Users/jaydenl/Dev/AI/YOLO-Test/test.py", line 31, in <module>
    tracker_outputs = tracker.update(annotated_frame.cpu().boxes.data, frame)
  File "/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/boxmot/botsort/bot_sort.py", line 310, in update
    detections = [STrack(xyxy, s, c, f.cpu().numpy()) for
  File "/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/boxmot/botsort/bot_sort.py", line 310, in <listcomp>
    detections = [STrack(xyxy, s, c, f.cpu().numpy()) for
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
(venv) ➜  YOLO-Test 
```

I'm using a custom trained yolov8 model using ultralytics and loading it from `best.pt`. The ultralytics library's tracking method `results = model.track(source="vid.mp4", show=True, tracker="botsort.yaml")` works fine, but I want to experiment with different algorithms.

### Environment

- ultralytics==8.0.98
- python 3.9.16
- OS: M1 Macbook Pro

### Minimal Reproducible Example

```py
import cv2
from ultralytics import YOLO
from boxmot import DeepOCSORT, StrongSORT, BoTSORT
from pathlib import Path
# from google.colab.patches import cv2_imshow
import numpy as np

# Load the YOLOv8 model
model = YOLO('best.pt')
# results = model.track(source="vid.mp4", show=True, tracker="botsort.yaml") 

tracker = BoTSORT(
  model_weights=Path('mobilenetv2_x1_4_dukemtmcreid.pt'),  # which ReID model to use, when applicable
  device='cpu',  # 'cpu', 'cuda:0', 'cuda:1', ... 'cuda:N'
  fp16=False,  # wether to run the ReID model with half precision or not
#   det_thresh=0.2  # minimum valid detection confidence
)

# Open the video file
cap = cv2.VideoCapture("vid.mp4")

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 inference on the frame
        results = model(frame, device="cpu")
        annotated_frame = results[0]
        tracker_outputs = tracker.update(annotated_frame.cpu().boxes.data, frame)
        bboxes = tracker_outputs[:, :4]
        id = tracker_outputs[:, 4]
        confidences = tracker_outputs[:, 5]
        classes = tracker_outputs[:, 6]
        
        for bbox, id, conf, cls in zip(bboxes, id, confidences, classes):
            bbox = bbox.astype(np.int32)
            x1, y1, x2, y2 = bbox
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(frame, f'{id} {conf:.2f} {cls}', (x1, y1), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)

        # Display the annotated frame
        cv2.imshow("YOLOv8 Inference",frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
```

**Comment by mikel-brostrom** [comment]
Have you tried to modofy this:

`tracker_outputs = tracker.update(annotated_frame.cpu().boxes.data, frame)`

to

`tracker_outputs = tracker.update(annotated_frame.detach().cpu().boxes.data, frame)`

**Comment by sqwatato** [comment]
Just tried it. Says `AttributeError: 'Results' object has no attribute 'detach'.`
Full error:
```
(venv) ➜  YOLO-Test python test.py
/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/examples/weights
/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/examples
Successfully loaded pretrained weights from "mobilenetv2_x1_4_dukemtmcreid.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

0: 416x256 26 heads, 57 persons, 30.7ms
Speed: 2.0ms preprocess, 30.7ms inference, 0.7ms postprocess per image at shape (1, 3, 416, 416)
Traceback (most recent call last):
  File "/Users/jaydenl/Dev/AI/YOLO-Test/test.py", line 38, in <module>
    tracker_outputs = tracker.update(annotated_frame.detach().cpu().boxes.data, frame)
  File "/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 135, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'Results' object has no attribute 'detach'. See valid attributes below.

    A class for storing and manipulating inference results.

    Args:
        orig_img (numpy.ndarray): The original image as a numpy array.
        path (str): The path to the image file.
        names (dict): A dictionary of class names.
        boxes (List[List[float]], optional): A list of bounding box coordinates for each detection.
        masks (numpy.ndarray, optional): A 3D numpy array of detection masks, where each mask is a binary image.
        probs (numpy.ndarray, optional): A 2D numpy array of detection probabilities for each class.
        keypoints (List[List[float]], optional): A list of detected keypoints for each object.


    Attributes:
        orig_img (numpy.ndarray): The original image as a numpy array.
        orig_shape (tuple): The original image shape in (height, width) format.
        boxes (Boxes, optional): A Boxes object containing the detection bounding boxes.
        masks (Masks, optional): A Masks object containing the detection masks.
        probs (numpy.ndarray, optional): A 2D numpy array of detection probabilities for each class.
        names (dict): A dictionary of class names.
        path (str): The path to the image file.
        keypoints (List[List[float]], optional): A list of detected keypoints for each object.
        speed (dict): A dictionary of preprocess, inference and postprocess speeds in milliseconds per image.
        _keys (tuple): A tuple of attribute names for non-empty attributes.
    
(venv) ➜  YOLO-Test 
```

**Comment by mikel-brostrom** [comment]
Oh sorry. I meant:

`tracker_outputs = tracker.update(annotated_frame.boxes.data.detach().cpu(), frame)`

**Comment by sqwatato** [comment]
Same issue as before. `RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.`

Full error:

```
(venv) ➜  YOLO-Test python test.py
/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/examples/weights
/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/examples
Successfully loaded pretrained weights from "mobilenetv2_x1_4_dukemtmcreid.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

0: 416x256 26 heads, 57 persons, 27.8ms
Speed: 1.5ms preprocess, 27.8ms inference, 0.5ms postprocess per image at shape (1, 3, 416, 416)
Traceback (most recent call last):
  File "/Users/jaydenl/Dev/AI/YOLO-Test/test.py", line 38, in <module>
    tracker_outputs = tracker.update(annotated_frame.boxes.data.detach().cpu(), frame)
  File "/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/boxmot/botsort/bot_sort.py", line 310, in update
    detections = [STrack(xyxy, s, c, f.cpu().numpy()) for
  File "/Users/jaydenl/Dev/AI/YOLO-Test/venv/lib/python3.9/site-packages/boxmot/botsort/bot_sort.py", line 310, in <listcomp>
    detections = [STrack(xyxy, s, c, f.cpu().numpy()) for
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
(venv) ➜  YOLO-Test 
```

**Comment by mikel-brostrom** [comment]
Found the issue. Just waiting for the CI to pass for merging

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/pull/911

**Comment by mikel-brostrom** [comment]
Ok. I know the reason. 

When not run with track.py, the ReID-based tracking methods don't get affected by:

https://github.com/mikel-brostrom/yolo_tracking/blob/b2f11989205b2a55d853f61e3c07a99d172046e3/examples/track.py#L48

So this has to be added for each of them

**Comment by sqwatato** [comment]
Works perfectly! Thanks!
