### ISSUE TITLE
cuda out of memory when I run tracking,  显存持续增长 显存持续增长 Continuous growth of graphics memory

### ISSUE THREAD

**Issue by lgf821793883** [mikel-brostrom/yolo_tracking#916]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

Traceback (most recent call last):
  File "work_dir/track.py", line 9, in <module>
    results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True) 
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 276, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 253, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 184, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 260, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 165, in write_results
    self.plotted_img = result.plot(**plot_args)
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/engine/results.py", line 222, in plot
    annotator.masks(pred_masks.data, colors=[colors(x, True) for x in idx], im_gpu=img_gpu)
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/utils/plotting.py", line 132, in masks
    inv_alph_masks = (1 - masks * alpha).cumprod(0)  # shape(n,h,w,1)
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/_tensor.py", line 40, in wrapped
    return f(*args, **kwargs)
  File "/home/xiashu/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/_tensor.py", line 848, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.90 GiB total capacity; 6.25 GiB already allocated; 54.31 MiB free; 6.69 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Environment

Ubuntu20.04 
P4000
Cuda 11.6

ultralytics              8.0.108

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model
model = YOLO('weights/yolov8s.pt')  # load an official detection model
model = YOLO('weights/yolov8s-seg.pt')  # load an official segmentation model
# model = YOLO('/home/xiashu/桌面/dev/xiashu/ultralytics/runs/segment/train15/weights/best.pt')  # load a custom model

# Track with the model
results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True) 
# results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True, tracker="bytetrack.yaml")

**Comment by mikel-brostrom** [comment]
Sorry, you are not using the repo the way it is intended. I have nothing to do with this way of running Yolov8 tracking:
`results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True)`
