### ISSUE TITLE
TensorRT engine does not run.

### ISSUE THREAD

**Issue by ss-hyun** [mikel-brostrom/yolo_tracking#945]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

I used the model exported from yolov8 to engine in the master branch to operate the tracker, but the following error occurred.

```
Traceback (most recent call last):
  File "examples/track.py", line 223, in <module>
    main(opt)
  File "examples/track.py", line 218, in main
    run(vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "examples/track.py", line 74, in run
    predictor.args.imgsz = check_imgsz(predictor.args.imgsz, stride=model.model.stride, min_dim=2)  # check image size
AttributeError: 'str' object has no attribute 'stride'
```

### Environment
```
2023-06-14 21:29:40.806 | INFO     | boxmot.utils.torch_utils:select_device:52 - Yolo Tracking v10.0.13 🚀 Python-3.8.10 torch-1.12.0a0+02fb0b0f.nv22.06 CUDA:0 (Xavier, 6857MiB)
```
```

2023-06-14 21:29:40.807 | INFO     | __main__:run:66 - {'yolo_model': PosixPath('models/yolov8s-aihub-coco-best.engine'), 'reid_model': PosixPath('models/osnet_ain_x1_0_msmt17.pt'), 'tracking_method': 'deepocsort', 'source': 'datasets/su1.mp4', 'imgsz': [640], 'conf': 0.5, 'iou': 0.7, 'device': '', 'show': False, 'save': False, 'classes': None, 'project': 'outputs/', 'name': 'exp', 'exist_ok': False, 'half': False, 'vid_stride': 5, 'hide_label': False, 'hide_conf': False, 'save_txt': False}
Loading models/yolov8s-aihub-coco-best.engine for TensorRT inference...
[06/14/2023-21:29:46] [TRT] [I] [MemUsageChange] Init CUDA: CPU +186, GPU +0, now: CPU 290, GPU 3855 (MiB)
[06/14/2023-21:29:47] [TRT] [I] Loaded engine size: 61 MiB
[06/14/2023-21:29:59] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +345, GPU +544, now: CPU 724, GPU 4541 (MiB)
[06/14/2023-21:29:59] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +61, now: CPU 0, GPU 61 (MiB)
[06/14/2023-21:29:59] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +18, now: CPU 663, GPU 4503 (MiB)
[06/14/2023-21:30:01] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +38, now: CPU 0, GPU 99 (MiB)
```

### Minimal Reproducible Example

```
#!/bin/bash
MODEL_PATH="models/"
OUTPUT_DIR="outputs/"

function run() {
    echo $1
    python3 examples/track.py \
        --yolo-model "${MODEL_PATH}yolov8s-aihub-coco-best.engine" \
        --tracking-method deepocsort \
        --reid-model "${MODEL_PATH}osnet_ain_x1_0_msmt17.pt" \
        --project $OUTPUT_DIR \
        --source "$1" \
        --vid-stride 5
}

run datasets/su1.mp4
```

**Comment by ss-hyun** [comment]
And this problem also occurs when using the onnx file. There's no problem using the pt file.
```
2023-06-15 11:27:24.997 | INFO     | boxmot.utils.torch_utils:select_device:52 - Yolo Tracking v10.0.13 🚀 Python-3.8.10 torch-1.12.0a0+02fb0b0f.nv22.06 CUDA:0 (Xavier, 6857MiB)

2023-06-15 11:27:24.998 | INFO     | __main__:run:66 - {'yolo_model': PosixPath('models/yolov8s-aihub-coco-best.onnx'), 'reid_model': PosixPath('models/osnet_ain_x1_0_msmt17.pt'), 'tracking_method': 'deepocsort', 'source': 'datasets/su1.mp4', 'imgsz': [640], 'conf': 0.5, 'iou': 0.7, 'device': '', 'show': False, 'save': False, 'classes': None, 'project': 'outputs/', 'name': 'exp', 'exist_ok': False, 'half': False, 'vid_stride': 5, 'hide_label': False, 'hide_conf': False, 'save_txt': False}
Loading models/yolov8s-aihub-coco-best.onnx for ONNX Runtime inference...
Traceback (most recent call last):
  File "examples/track.py", line 222, in <module>
    main(opt)
  File "examples/track.py", line 217, in main
    run(vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "examples/track.py", line 73, in run
    predictor.args.imgsz = check_imgsz(predictor.args.imgsz, stride=model.model.stride, min_dim=2)  # check image size
AttributeError: 'str' object has no attribute 'stride'
```

**Comment by ss-hyun** [comment]
Isn't this problem going to be solved?
