### ISSUE TITLE
FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by yassminSaber** [mikel-brostrom/yolo_tracking#952]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

2023-06-16 18:01:31.897 | INFO     | boxmot.utils.torch_utils:select_device:52 - Yolo Tracking v10.0.14 🚀 Python-3.10.12 torch-2.0.1+cu118 CPU

2023-06-16 18:01:31.898 | INFO     | __main__:run:66 - {'yolo_model': PosixPath('yolov8s.pt'), 'reid_model': PosixPath('lmbn_n_cuhk03_d.pt'), 'tracking_method': 'deepocsort', 'source': '/content/drive/MyDrive/CarsOnHighway.mp4', 'imgsz': [640], 'conf': 0.5, 'iou': 0.7, 'device': '', 'show': True, 'save': True, 'classes': [2, 3, 4, 6, 8], 'project': PosixPath('/usr/local/lib/python3.10/dist-packages/runs/track'), 'name': 'exp', 'exist_ok': False, 'half': False, 'vid_stride': 1, 'hide_label': False, 'hide_conf': False, 'save_txt': False}
Traceback (most recent call last):
  File "/content/yolov8_tracking/examples/track.py", line 222, in <module>
    main(opt)
  File "/content/yolov8_tracking/examples/track.py", line 217, in main
    run(vars(opt))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/yolov8_tracking/examples/track.py", line 85, in run
    predictor.run_callbacks('on_predict_start')
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/predictor.py", line 339, in run_callbacks
    callback(self)
  File "/content/yolov8_tracking/examples/track.py", line 41, in on_predict_start
    tracker = create_tracker(
  File "/usr/local/lib/python3.10/dist-packages/boxmot/tracker_zoo.py", line 18, in create_tracker
    with open(tracker_config, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/boxmot/deepocsort/configs/deepocsort.yaml'

### Environment

python-3.10.12

### Minimal Reproducible Example

!python yolov8_tracking/examples/track.py --tracking-method deepocsort --source /content/drive/MyDrive/CarsOnHighway.mp4  --reid-model lmbn_n_cuhk03_d.pt --yolo-model yolov8s.pt --classes 2 3 4 6 8  --save --show

**Comment by mikel-brostrom** [comment]
The file is there in master

https://github.com/mikel-brostrom/yolo_tracking/blob/master/boxmot/deepocsort/configs/deepocsort.yaml

You could copy it in case you accidentally deleted it
