### ISSUE TITLE
global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range

### ISSUE THREAD

**Issue by LinaZhangUSC** [mikel-brostrom/yolo_tracking#953]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

[32m2023-06-17 01:13:48.823[0m | [1mINFO    [0m | [36m__main__[0m:[36mrun[0m:[36m66[0m - [1m{'yolo_model': PosixPath('yolo_nas_s'), 'reid_model': PosixPath('/home1/linazhan/yolo_tracking/examples/weights/mobilenetv2_x1_4_dukemtmcreid.pt'), 'tracking_method': 'deepocsort', 'source': '0', 'imgsz': [640], 'conf': 0.5, 'iou': 0.7, 'device': '', 'show': False, 'save': False, 'classes': None, 'project': PosixPath('/home1/linazhan/yolo_tracking/runs/track'), 'name': 'exp', 'exist_ok': False, 'half': False, 'vid_stride': 1, 'hide_label': False, 'hide_conf': False, 'save_txt': False}[0m
[ WARN:0@5.767] global cap_v4l.cpp:982 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@5.769] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range
Traceback (most recent call last):
  File "examples/track.py", line 222, in <module>
    main(opt)
  File "examples/track.py", line 217, in main
    run(vars(opt))
  File "/home1/linazhan/.conda/envs/yolo/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "examples/track.py", line 71, in run
    predictor.setup_source(predictor.args.source)
  File "/home1/linazhan/.conda/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 197, in setup_source
    self.dataset = load_inference_source(source=source, imgsz=self.imgsz, vid_stride=self.args.vid_stride)
  File "/home1/linazhan/.conda/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/data/build.py", line 159, in load_inference_source
    dataset = LoadStreams(source, imgsz=imgsz, vid_stride=vid_stride)
  File "/home1/linazhan/.conda/envs/yolo/lib/python3.8/site-packages/ultralytics/yolo/data/dataloaders/stream_loaders.py", line 55, in __init__
    raise ConnectionError(f'{st}Failed to open {s}')
ConnectionError: 1/1: 0... Failed to open 0

### Environment

1

### Minimal Reproducible Example

1

**Comment by mikel-brostrom** [comment]
Seems like your built-in camera isn't available

**Comment by LinaZhangUSC** [comment]
> Seems like your built-in camera isn't available
so how to make it available. I tried it by set some environment variables but failed

**Comment by mikel-brostrom** [comment]
There are plenty of resources for this on stackoverflow
