### ISSUE TITLE
No module named 'ultralytics'

### ISSUE THREAD

**Issue by NaifahNurya** [mikel-brostrom/yolo_tracking#958]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I have followed all the instructions on how to setup and install on README.md. 
However, when run val.py for starting evaluating my custom dataset (as presented in procedure 0. for how to run 
on custom dataset, got the following error;

```
Missing packages: "lap>=0.4"
Atempting installation...
2023-06-18 10:32:42.714 | SUCCESS  | boxmot.utils.checks:check_packages:33 - All the missing packages were installed successfully
Traceback (most recent call last):
  File "val.py", line 31, in <module>
    from ultralytics.yolo.utils.checks import check_requirements, print_args
ModuleNotFoundError: No module named 'ultralytics'
```

Thereafter, after running the following command 
`python val.py --yolo-model weights/yolox_x.pth --benchmark MOTCUSTOM --split test --tracking-method bytetrack`

for evaluating the performance of ByteTrack with yolox detector trained model on my customdatset got the following error again
```
Traceback (most recent call last):
  File "val.py", line 31, in <module>
    from ultralytics.yolo.utils.checks import check_requirements, print_args
ModuleNotFoundError: No module named 'ultralytics'
```

Is there a way of resolving this issue. I use the current updated version of the yolo_tracking.

**Comment by mikel-brostrom** [comment]
I see the issue. Run `track.py` once and the `ultralytics` package will get automatically downloaded. Need to find time to find a better fix

**Comment by NaifahNurya** [comment]
Thank you for reply, I did as you suggested. The reported error now is no longer existing.
However, I got the following error on evaluating Bytetrack with yolox
 
ERROR    | __main__:eval:260 - C:\Users\IDB\anaconda3\envs\yolomsetotracking\python.exe: can't open file 'C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\scripts\run_mot_challenge.py': [Errno 2] No such file or directory



The following is detailed information:

```
(yolotracking) C:\Users\Adm\Desktop\yolo_tracking>python examples/val.py --yolo-model examples/weights/yolox_x.pth --benchmark MOTCUSTOM --split test --tracking-method bytetrack
val: yolo_model=examples/weights/yolox_x.pth, reid_model=C:\Users\Adm\Desktop\yolo_tracking\examples\weights\mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=bytetrack, name=exp, classes=['0'], project=C:\Users\Adm\Desktop\yolo_tracking\examples\runs\val, exist_ok=False, benchmark=MOTCUSTOM, split=test, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
2023-06-18 18:29:11.441 | INFO     | __main__:download_mot_eval_tools:64 - Eval repo already downloaded
2023-06-18 18:29:11.445 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V000\V000
2023-06-18 18:30:55.605 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V000\V000 evaluation succeeded
2023-06-18 18:30:55.608 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V001\V001
2023-06-18 18:31:52.655 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V001\V001 evaluation succeeded
2023-06-18 18:31:52.658 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V002\V002
2023-06-18 18:33:23.081 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V002\V002 evaluation succeeded
2023-06-18 18:33:23.084 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V003\V003
2023-06-18 18:34:16.940 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V003\V003 evaluation succeeded
2023-06-18 18:34:16.944 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V004\V004
2023-06-18 18:35:47.710 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V004\V004 evaluation succeeded
2023-06-18 18:35:47.714 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V005\V005
2023-06-18 18:36:40.593 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V005\V005 evaluation succeeded
val: yolo_model=examples/weights/yolox_x.pth, reid_model=C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\weights\mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=bytetrack, name=exp, classes=['0'], project=C:\Users\Adm\Desktop\yolo_tracking\examples\runs\val, exist_ok=False, benchmark=MOTCUSTOM, split=test, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
2023-06-18 18:36:40.680 | ERROR    | __main__:eval:260 - C:\Users\Adm\anaconda3\envs\yolotracking\python.exe: can't open file 'C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\scripts\run_mot_challenge.py': [Errno 2] No such file or directory

2023-06-18 18:36:40.684 | ERROR    | __main__:eval:261 -

```

**Comment by NaifahNurya** [comment]
Sorry for the reporting the above error, It was solved after running `python val.py`

But, after running again to evaluate my custom dataset, the following error happen, and no results

```
(yolotracking) C:\Users\Adm\Desktop\yolo_tracking>python examples/val.py --yolo-model examples/weights/yolox_x.pth --benchmark MOTCUSTOM --split test --tracking-method bytetrack
val: yolo_model=examples/weights/yolox_x.pth, reid_model=C:\Users\Adm\Desktop\yolo_tracking\examples\weights\mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=bytetrack, name=exp, classes=['0'], project=C:\Users\Adm\Desktop\yolo_tracking\examples\runs\val, exist_ok=False, benchmark=MOTCUSTOM, split=test, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
2023-06-18 18:29:11.441 | INFO     | __main__:download_mot_eval_tools:64 - Eval repo already downloaded
2023-06-18 18:29:11.445 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V000\V000
2023-06-18 18:30:55.605 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V000\V000 evaluation succeeded
2023-06-18 18:30:55.608 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V001\V001
2023-06-18 18:31:52.655 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V001\V001 evaluation succeeded
2023-06-18 18:31:52.658 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V002\V002
2023-06-18 18:33:23.081 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V002\V002 evaluation succeeded
2023-06-18 18:33:23.084 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V003\V003
2023-06-18 18:34:16.940 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V003\V003 evaluation succeeded
2023-06-18 18:34:16.944 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V004\V004
2023-06-18 18:35:47.710 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V004\V004 evaluation succeeded
2023-06-18 18:35:47.714 | INFO     | __main__:eval:195 - Staring evaluation process on C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V005\V005
2023-06-18 18:36:40.593 | SUCCESS  | __main__:eval:227 - C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test\V005\V005 evaluation succeeded
val: yolo_model=examples/weights/yolox_x.pth, reid_model=C:\Users\Adm\Desktop\MSETO\yolo_tracking\examples\weights\mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=bytetrack, name=exp, classes=['0'], project=C:\Users\Adm\Desktop\yolo_tracking\examples\runs\val, exist_ok=False, benchmark=MOTCUSTOM, split=test, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2

2023-06-18 19:13:18.827 | ERROR    | __main__:eval:260 - Traceback (most recent call last):
  File "C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\scripts\run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\trackeval\datasets\mot_challenge_2d_box.py", line 82, in __init__
    self.seq_list, self.seq_lengths = self._get_seq_info()
  File "C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\trackeval\datasets\mot_challenge_2d_box.py", line 146, in _get_seq_info
    seq_lengths[seq] = int(ini_data['Sequence']['seqLength'])
ValueError: invalid literal for int() with base 10: '<1038>'

2023-06-18 19:13:18.830 | ERROR    | __main__:eval:261 - Error importing BURST due to missing underlying dependency: No module named 'pycocotools'

Eval Config:
USE_PARALLEL         : True
NUM_PARALLEL_CORES   : 4
BREAK_ON_ERROR       : True
RETURN_ON_ERROR      : False
LOG_ON_ERROR         : C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\error_log.txt
PRINT_RESULTS        : True
PRINT_ONLY_COMBINED  : False
PRINT_CONFIG         : True
TIME_PROGRESS        : True
DISPLAY_LESS_PROGRESS : False
OUTPUT_SUMMARY       : True
OUTPUT_EMPTY_CLASSES : True
OUTPUT_DETAILED      : True
PLOT_CURVES          : True

MotChallenge2DBox Config:
PRINT_CONFIG         : True
GT_FOLDER            : C:\Users\Adm\Desktop\yolo_tracking\examples\val_utils\data\MOTCUSTOM\test
TRACKERS_FOLDER      : C:\Users\Adm\Desktop\yolo_tracking\examples\runs\val\exp3
OUTPUT_FOLDER        : None
TRACKERS_TO_EVAL     : ['labels']
CLASSES_TO_EVAL      : ['pedestrian']
BENCHMARK            :
SPLIT_TO_EVAL        : train
INPUT_AS_ZIP         : False
DO_PREPROC           : True
TRACKER_SUB_FOLDER   :
OUTPUT_SUB_FOLDER    :
TRACKER_DISPLAY_NAMES : None
SEQMAP_FOLDER        : None
SEQMAP_FILE          : None
SEQ_INFO             : {'V000': None, 'V001': None, 'V002': None, 'V003': None, 'V004': None, 'V005': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt
SKIP_SPLIT_FOL       : True

```

**Comment by mikel-brostrom** [comment]
Something seems to be wrong with your ini file, based on this:

```
    seq_lengths[seq] = int(ini_data['Sequence']['seqLength'])
ValueError: invalid literal for int() with base 10: '<1038>'
```

double check the format of this file

**Comment by NaifahNurya** [comment]
Thank you very much, It was the problem on the seqinfo.ini file. 

I put the seqLength=<int> #as it was show on the documentation.

After changing it to;
`seqLength=int  #eg seqLength=1038`

the problem solved.
