### ISSUE TITLE
After 4 frames getting an Error from the tracker : numpy.AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by Nuwan1654** [mikel-brostrom/yolo_tracking#962]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

Traceback (most recent call last):
  File "./test_inference.py", line 332, in <module>
    main(args_in)
  File "./test_inference.py", line 216, in main
    online_targets = catogorized_trackers[key].update(detections, frame)
  File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/strong_sort.py", line 237, in update
    self.tracker.update(detections, clss, confs)
  File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/tracker.py", line 91, in update
    self._match(detections)
  File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/tracker.py", line 168, in _match
    linear_assignment.matching_cascade(
  File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/linear_assignment.py", line 123, in matching_cascade
    min_cost_matching(
  File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/linear_assignment.py", line 52, in min_cost_matching
    cost_matrix = distance_metric(
  File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/tracker.py", line 155, in gated_metric
    cost_matrix = self.metric.distance(features, targets)
  File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/nn_matching.py", line 162, in distance
    cost_matrix[i, :] = self._metric(self.samples[target], features)
  File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/nn_matching.py", line 90, in _nn_cosine_distance
    distances = _cosine_distance(x_, y_)
  File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/nn_matching.py", line 49, in _cosine_distance
    a = np.asarray(a) / np.linalg.norm(a, axis=1, keepdims=True)
  File "<__array_function__ internals>", line 180, in norm
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 2557, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

### Environment

Python: Python 3.8.10-64-bit

Device:
Jetson Orin

OS:
Ubuntu 20.04.4 LTS 
Linux ubuntu 5.10.104-tegra 

GPU : 

CUDA: 11.4
CUDNN: 8.6.0
TensorRT: 8.5.2

### Minimal Reproducible Example

'''
from boxmot import StrongSORT
from pathlib import Path

tracker = StrongSORT(
  model_weights=Path('osnet_x0_25_msmt17.pt'),  # which ReID model to use
  device='cuda:0',  
  fp16=True,  
)
  
cap = cv.VideoCapture(0)
while True:
    ret, im = cap.read()
    dets = inference(im)
    tracker_outputs = tracker.update(dets, im)  # --> (x, y, x, y, id, conf, cls)

'''

**Comment by mikel-brostrom** [comment]
Sorry, cannot reproduce. I have zero problems running this:

```python
from boxmot import StrongSORT
from pathlib import Path
import cv2 as cv
import numpy as np

tracker = StrongSORT(
    model_weights=Path('osnet_x0_25_msmt17.pt'), # which ReID model to use
    device='cuda:0',
    fp16=True,
)

cap = cv.VideoCapture(0)
while True:
    ret, im = cap.read()
    dets = np.array([[144, 212, 578, 480, 0.82, 0],
                    [425, 281, 576, 472, 0.56, 65]])
    tracker_outputs = tracker.update(dets, im) # --> (x, y, x, y, id, conf, cls)
    print(tracker_outputs)
```

results:

```bash
(env) ➜  yolov8_tracking git:(master) ✗ python3 testff.py
2023-06-20 09:13:43.134 | SUCCESS  | boxmot.deep.reid_model_factory:load_pretrained_weights:229 - Successfully loaded pretrained weights from "osnet_x0_25_msmt17.pt"
2023-06-20 09:13:43.134 | WARNING  | boxmot.deep.reid_model_factory:load_pretrained_weights:233 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')

[]
[]
[[1.43e+02 2.12e+02 5.78e+02 4.79e+02 1.00e+00 8.20e-01 0.00e+00]
 [4.24e+02 2.81e+02 5.76e+02 4.72e+02 2.00e+00 5.60e-01 6.50e+01]]
[[1.43e+02 2.12e+02 5.78e+02 4.79e+02 1.00e+00 8.20e-01 0.00e+00]
 [4.24e+02 2.81e+02 5.76e+02 4.72e+02 2.00e+00 5.60e-01 6.50e+01]]
[[1.43e+02 2.12e+02 5.78e+02 4.79e+02 1.00e+00 8.20e-01 0.00e+00]
 [4.24e+02 2.81e+02 5.76e+02 4.72e+02 2.00e+00 5.60e-01 6.50e+01]]
[[1.43e+02 2.12e+02 5.78e+02 4.79e+02 1.00e+00 8.20e-01 0.00e+00]
 [4.24e+02 2.81e+02 5.76e+02 4.72e+02 2.00e+00 5.60e-01 6.50e+01]]
[[1.43e+02 2.12e+02 5.78e+02 4.79e+02 1.00e+00 8.20e-01 0.00e+00]
 [4.24e+02 2.81e+02 5.76e+02 4.72e+02 2.00e+00 5.60e-01 6.50e+01]]
[[1.43e+02 2.12e+02 5.78e+02 4.79e+02 1.00e+00 8.20e-01 0.00e+00]
 [4.24e+02 2.81e+02 5.76e+02 4.72e+02 2.00e+00 5.60e-01 6.50e+01]]
[[1.43e+02 2.12e+02 5.78e+02 4.79e+02 1.00e+00 8.20e-01 0.00e+00]
 [4.24e+02 2.81e+02 5.76e+02 4.72e+02 2.00e+00 5.60e-01 6.50e+01]]
[[1.43e+02 2.12e+02 5.78e+02 4.79e+02 1.00e+00 8.20e-01 0.00e+00]
 [4.24e+02 2.81e+02 5.76e+02 4.72e+02 2.00e+00 5.60e-01 6.50e+01]]
```

**Comment by mikel-brostrom** [comment]
Maybe I should add asserts in the trackers for checking the input shapes...

**Comment by Nuwan1654** [comment]
Hi @mikel-brostrom , Sorry for my short explanation of the error. clearly, this is not happening with running directly from the repo.

My requirement is to run a yolov7 model and the strong sort tracker in the jetson with higher FPS. flowing similar to [this](https://forums.developer.nvidia.com/t/unable-to-run-two-tensorrt-models-in-a-cascade-manner/145274)

I have changed the feature extraction model inference to a custom code to make it run faster in the jetson. Because when I tried to run the feature extraction model (converted to a tensorRT engine) in the jetson FPS was low at 3-4. So I changed the inference code.   

I have no idea about the place where the above error is generated. can you please provide some insight into the error message? 

```
File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/tracker.py", line 91, in update
self._match(detections)
File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/tracker.py", line 168, in _match
linear_assignment.matching_cascade(
File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/linear_assignment.py", line 123, in matching_cascade
min_cost_matching(
File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/linear_assignment.py", line 52, in min_cost_matching
cost_matrix = distance_metric(
File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/tracker.py", line 155, in gated_metric
cost_matrix = self.metric.distance(features, targets)
File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/nn_matching.py", line 162, in distance
cost_matrix[i, :] = self._metric(self.samples[target], features)
File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/nn_matching.py", line 90, in nn_cosine_distance
distances = cosine_distance(x, y)
File "/home/zoomi2023/dinusha/strong-sort/shelf-guard/trackers/strongsort/sort/nn_matching.py", line 49, in _cosine_distance
a = np.asarray(a) / np.linalg.norm(a, axis=1, keepdims=True)
File "<array_function internals>", line 180, in norm
File "/home/zoomi2023/.local/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 2557, in norm
return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```

Any help would be highly appreciated. 
Thanks

**Comment by mikel-brostrom** [comment]
Please, assert that the types and the shapes are correct:

```python
    # dets (numpy.ndarray): 
    #  - your model's nms:ed outputs of shape Nx6 (x, y, x, y, conf, cls)
    # im   (numpy.ndarray):
    #  - the original hxwx3 image (for better ReID results)
    #  - the downscaled hxwx3 image fed to you model (faster)
```

if you still get the problem get back at me

**Comment by Nuwan1654** [comment]
I found the error, In my custom inference code I had to reshape the output 

features = trt_outputs[0].reshape(-1, 512)

Thanks for the help. :)
