### ISSUE TITLE
getting error while testing person tracking module

### ISSUE THREAD

**Issue by dsnsabari** [mikel-brostrom/yolo_tracking#981]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking, Evaluation

### Bug

**The command used for testing:**

```
python examples/val.py --yolo-model yolox_n.pt    --reid-model osnet_ain_x1_0_msmt17.pt  --tracking-method ocsort     --benchmark MOT17

```

**Error:**

```
  0%|          | 0.00/6.23M [00:00<?, ?B/s]
 36%|###5      | 2.23M/6.23M [00:00<00:00, 23.1MB/s]
 82%|########2 | 5.14M/6.23M [00:00<00:00, 26.9MB/s]
100%|##########| 6.23M/6.23M [00:00<00:00, 26.9MB/s]
Traceback (most recent call last):
  File "D:\Person_Tracking\yolo_tracking\examples\track.py", line 234, in <module>
    main(opt)
  File "D:\Person_Tracking\yolo_tracking\examples\track.py", line 229, in main
    run(vars(opt))
  File "C:\Users\SABARI\Anaconda3\envs\pytorch_env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Person_Tracking\yolo_tracking\examples\track.py", line 56, in run
    model.predictor = TASK_MAP[model.task][3](overrides=overrides, _callbacks=model.callbacks)
  File "C:\Users\SABARI\Anaconda3\envs\pytorch_env\lib\site-packages\ultralytics\yolo\engine\model.py", line 113, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'YOLO' object has no attribute 'callbacks'. See valid attributes below.

    YOLO (You Only Look Once) object detection model.

    Args:
        model (str, Path): Path to the model file to load or create.

    Attributes:
        predictor (Any): The predictor object.
        model (Any): The model object.
        trainer (Any): The trainer object.
        task (str): The type of model task.
        ckpt (Any): The checkpoint object if the model loaded from *.pt file.
        cfg (str): The model configuration if loaded from *.yaml file.
        ckpt_path (str): The checkpoint file path.
        overrides (dict): Overrides for the trainer object.
        metrics (Any): The data for metrics.

    Methods:
        __call__(source=None, stream=False, **kwargs):
            Alias for the predict method.
        _new(cfg:str, verbose:bool=True) -> None:
            Initializes a new model and infers the task type from the model definitions.
        _load(weights:str, task:str='') -> None:
            Initializes a new model and infers the task type from the model head.
        _check_is_pytorch_model() -> None:
            Raises TypeError if the model is not a PyTorch model.
        reset() -> None:
            Resets the model modules.
        info(verbose:bool=False) -> None:
            Logs the model info.
        fuse() -> None:
            Fuses the model for faster inference.
        predict(source=None, stream=False, **kwargs) -> List[ultralytics.yolo.engine.results.Results]:
            Performs prediction using the YOLO model.

    Returns:
        list(ultralytics.yolo.engine.results.Results): The prediction results.
```

### Environment

Windows 10

Python 3.9.12

Pytorch Version : 2.0.1+cu117

### Minimal Reproducible Example

```
python examples/val.py --yolo-model yolox_n.pt    --reid-model osnet_ain_x1_0_msmt17.pt  --tracking-method ocsort     --benchmark MOT17


```

**Comment by mikel-brostrom** [comment]
Sorry cannot reproduce. Could you provide which ultralytics version you are using? `pip list | grep 'ultralytics'`

**Comment by mikel-brostrom** [comment]
Make sure you have `8.0.124` installed :smile:

**Comment by dsnsabari** [comment]
@mikel-brostrom , thank you so much for the quick reply. I solved the issue. I want to change the output label.   

I want to display the track_id in the results. Which script should I change to get the track id only in the results ? 

**Command used for testing:**

```
python examples/val.py -yolo-model yolov8s.pt    --reid-model lmbn_n_market.pt --tracking-method strongsort --benchmark MOT17

```
![000002](https://github.com/mikel-brostrom/yolo_tracking/assets/46018083/0d3335e9-9985-4240-af92-b6c7d474bb81)

**Comment by mikel-brostrom** [comment]
The output looks alright on my side. The is present

![000005](https://github.com/mikel-brostrom/yolo_tracking/assets/18719680/2423e53c-af1b-4087-a45d-ba084a9cc5da)

**Comment by dsnsabari** [comment]
@mikel-brostrom , I would like to display the track_id only for my testing purpose. Please point out the script which I can change for testing purposes. I tried to find the module, but I am not able to find it. 

I don't want to display the object label and confidence score.. Please tell me the script line or script name. I will change it for my testing.

**Comment by dsnsabari** [comment]
@mikel-brostrom ,  how to remove the person and confidence score in the results?  

if the below script draws the results, could you tell me which one should i remove it. 

 https://github.com/mikel-brostrom/yolo_tracking/blob/master/boxmot/strongsort/utils/draw.py#L29

**Comment by mikel-brostrom** [comment]
I actually don't know if this works but you could try to add:

```python
    parser.add_argument('--hide-labels', action='store_true')
    parser.add_argument('--hide-conf', action='store_true')
```

to arguments and then run:

`python examples/val.py -yolo-model yolov8s.pt    --reid-model lmbn_n_market.pt --tracking-method strongsort --benchmark MOT17 --hide-labels --hide-conf`

**Comment by mikel-brostrom** [comment]
I see what the issue is. Give me 5 minutes

**Comment by dsnsabari** [comment]
@mikel-brostrom thank you so much

**Comment by dsnsabari** [comment]
@mikel-brostrom I am getting the below errors. 

```
-hide-con
usage: val.py [-h] [--yolo-model YOLO_MODEL] [--reid-model REID_MODEL] [--tracking-method TRACKING_METHOD] [--name NAME] [--classes CLASSES [CLASSES ...]] [--project PROJECT] [--exist-ok]
              [--benchmark BENCHMARK] [--split SPLIT] [--eval-existing] [--conf CONF] [--imgsz IMGSZ [IMGSZ ...]] [--device DEVICE] [--processes-per-device PROCESSES_PER_DEVICE]
val.py: error: unrecognized arguments: --hide-labels --hide-con
```

**Comment by dsnsabari** [comment]
@mikel-brostrom , I am getting the below errors.

```

-hide-conf
usage: val.py [-h] [--yolo-model YOLO_MODEL] [--reid-model REID_MODEL] [--tracking-method TRACKING_METHOD] [--name NAME] [--classes CLASSES [CLASSES ...]] [--project PROJECT] [--exist-ok]
              [--benchmark BENCHMARK] [--split SPLIT] [--eval-existing] [--conf CONF] [--imgsz IMGSZ [IMGSZ ...]] [--device DEVICE] [--processes-per-device PROCESSES_PER_DEVICE]
val.py: error: unrecognized arguments: --hide-labels --hide-conf

```

**Comment by dsnsabari** [comment]
@mikel-brostrom have you solved the issue?
